### ISSUE TITLE
Internal video player doesn't work with the latest version 1.4.1

### ISSUE THREAD

**Issue by jpfleury** [otsaloma/gaupol#102]
I manually installed the latest version 1.4.1 on Xubuntu 18.04 64-bit (windowing system: X11). All dependencies listed on the README file are installed (`python3 python3-gi python3-gi-cairo gir1.2-gtk-3.0 gettext gir1.2-gstreamer-1.0 gir1.2-gst-plugins-base-1.0 gstreamer1.0-gtk3 gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav python3-enchant gir1.2-gtkspell3-3.0 iso-codes python3-chardet`).

When selecting a video file, the internal player remains black. Clicking on the "Play" button below the internal player (or using the shortcut key "P") does nothing, and there's no output error in the terminal. Clicking on the "Play" button over opens the external player (and the video is played):

![gaupol-video-player](https://user-images.githubusercontent.com/687082/43305297-395720fc-9145-11e8-83bd-aa51df0fd1d3.jpg)

The internal video player worked with Gaupol 1.2 on Xubuntu 17.10.

**Comment by otsaloma** [comment]
Do you have `gstreamer1.0-vaapi` installed? If yes, try removing it, see #79.

**Comment by jpfleury** [comment]
I had this package installed. I removed it and it solved the problem. Now the internal video works great. Thanks!

I close this bug as a duplicate of #79.

**Comment by plutocrat** [comment]
Worked for me too, 5 years later!
