### ISSUE TITLE
Load video menu not active

### ISSUE THREAD

**Issue by iaubain** [otsaloma/gaupol#114]
Hello Gaupol team,
I am new to your tool but from the time I downloaded it it looks like the menu to load video Is not active and is un-clickable,
I open Gaupol
Click file, and new
I go to Video, then Load video is not active

An other thing is that on Win 10 it doesn't do a good rendering.

**Comment by otsaloma** [comment]
Windows support is indeed lacking. The integrated video player is disabled on Windows, it doesn't work, it's a known issue (#27). Rendering, at least font rendering, is probably still bad as Gaupol is a non-native app on Windows. It seems that Gtk is not actively developed or packaged for Windows, and also I don't use Windows myself, so the situation is unlikely to improve. In terms of features, you are likely to find better subtitle editor for use on Windows.

**Comment by iaubain** [comment]
> Windows support is indeed lacking. The integrated video player is disabled on Windows, it doesn't work, it's a known issue (#27). Rendering, at least font rendering, is probably still bad as Gaupol is a non-native app on Windows. It seems that Gtk is not actively developed or packaged for Windows, and also I don't use Windows myself, so the situation is unlikely to improve. In terms of features, you are likely to find better subtitle editors for use on Windows.

Thank you, for your honesty!
