### ISSUE TITLE
Can't install Gaupol

### ISSUE THREAD

**Issue by Pemicope** [otsaloma/gaupol#115]
Hello!

I can't install Gaupol using the following command: `sudo python3 setup.py install --prefix=/usr/local`
I get the following error on the terminal: `Traceback (most recent call last):
  File "setup.py", line 40, in <module>
    from distutils import log
ImportError: cannot import name 'log'`
I'm using elementary OS Juno, and I've also installed all the dependencies.

Thanks!

**Comment by otsaloma** [comment]
You probably need to install package "python3-dev". Please confirm if that works and I'll add it to the README file.

**Comment by Pemicope** [comment]
Yes, it worked!
Thank you very much! :+1:
