### ISSUE TITLE
Key bindings for italic

### ISSUE THREAD

**Issue by mkkot** [otsaloma/gaupol#118]
Hi there!
I wanted to translate an original srt file with lots of italics. I'm really missing the option for custom shortcut for this option, as typing the `<i>` tags or selecting menu option with mouse is insane with many dialogs. My proposal is ctrl + i.
![przechwycenie obrazu ekranu_2019-01-09_19-02-28](https://user-images.githubusercontent.com/10531790/50918690-3b30e280-1441-11e9-9bd3-b5aab042d400.png)

I wanted to change the code myself, but I couldn't find where shortcuts are defined...

**Comment by otsaloma** [comment]
`Ctrl+I` is already in use for "Invert Selection". `I` is also in use, for "Insert Subtitles". So, there's no good solution, but maybe I could add some weird letter and for these simple actions I'd leave out the Control.

> I wanted to change the code myself, but I couldn't find where shortcuts are defined...

There's no config. GTK2 had nice dynamic keybindings, but those didn't make it to GTK3. It would be possible to add an "accel" file to the configuration directory, but it's so undiscoverable and cryptic, that I don't think it would be of much use.

If you need something right now, you can change the key in the code, file `gaupol/actions/text.py`, class  `ToggleItalicizationAction`. Check the other classes to see how keys are defined.

**Comment by otsaloma** [comment]
This is what the "accel" files look like, eog (GNOME's "Image Viewer") as an exaple. It's a blank file, so it's really hard to know what to type in.

```scheme
; eog GtkAccelMap rc-file         -*- scheme -*-
; this file is an automated accelerator map dump
;
```

**Comment by mkkot** [comment]
Okay, I managed to change key bindings for italics. However I'm suprised it works only for whole dialog and not for text field. It would be useful to _italize_ only _some_ part of text, leaving the rest normal.

**Comment by otsaloma** [comment]
When editing, it's just a standard text view. It should be possible to add a context menu item and associated keybinding there, it could even be `Ctrl+I` as most of Gaupol's own actions are disabled while editing text.

**Comment by mkkot** [comment]
That would be really cool as italics are widely used for marking dialog which comes off the camera. I'm currently having a movie with only one actor who talks through the radio, so for me it looks like this:

![przechwycenie obrazu ekranu_2019-01-10_22-38-03](https://user-images.githubusercontent.com/10531790/50998695-85d95a00-1528-11e9-9b77-3ca2668e4f23.png)

**Comment by otsaloma** [comment]
![italic](https://user-images.githubusercontent.com/237265/51092983-ca722900-17a6-11e9-84fa-d936adaafe2a.png)

**Comment by otsaloma** [comment]
Both done now, both `Ctrl+I`.

**Comment by mkkot** [comment]
Thanks man! I have already translated the movie, but will check it later to see how it works ;)

**Comment by mkkot** [comment]
Yes, it works. I'm pretty suprised that microdvd format doesn't have possibility to close {y:i} tag, but seems that's a feature ;) Thanks again.
