### ISSUE TITLE
Display translation while watching video

### ISSUE THREAD

**Issue by mkkot** [otsaloma/gaupol#120]
Hello again,
I'm wondering if it is possible to display the translated subtitles in in-built video player? I find this more natural as I would like to see if my subtitles are looking well (not too long for example, if the exposition time is not too short).  Of course I'm talking about situation when I have opened original subtitle file and translation file at the same time.  Maybe there should be a switch which subtitles we want to display.

**Comment by otsaloma** [comment]
That's not possible, it's an intended simplification. It sounds weird to me to need the translation there. For long lines, you should rather rely on em or character counts rules. Duration is usually unchanged when translating and if you lengthen the duration and want to check it's not pushed past a scene change, you'll see that whichever text is shown. I just don't see a justification for the complexity. For what it's worth, the external video player will show either the original text or translation depending on which column is in focus.

**Comment by mkkot** [comment]
Sometimes you just want to see how your translation looks like. Your description sounds more like buying clothes online instead of actually wearing them ;) I didn't know about external player, that is also useful. And BTW, I was actually surprised at the beginning that gaupol shows original subtitles instead of translation. I can hear original track, I can see it on the left, I know it's done properly, but I'm working on the translation, so it's pretty obvious for me that the translation should be displayed by default. I thought that this was a bug, not a feature ;)
