### ISSUE TITLE
Aeidon: \r<Style> not supported

### ISSUE THREAD

**Issue by stuxcrystal** [otsaloma/gaupol#121]
I just found your project via the github "discover repositories" and found a bug.

In this line, a regex is defined for detecting the reset-Style tag:
https://github.com/otsaloma/gaupol/blob/c4a784c2a197a4dabc59505aefc2d97965dc4188/aeidon/markups/ssa.py#L56

According to [the Aegisub 3.2 Documentation](http://docs.aegisub.org/3.2/ASS_Tags/) there is a second form of reset-tag applies the style with the given name to the text after the reset.

This version is not handled by the parser.

**Comment by otsaloma** [comment]
Gaupol doesn't support all SSA/ASS tags, since they are complicated and difficult to map to other formats. Considering that, what exactly do you mean by "is not handled"? What doesn't work? What would you expect to happen?

**Comment by otsaloma** [comment]
And, did you notice that that SSA `_reset_pattern` is overridden in ASS.

https://github.com/otsaloma/gaupol/blob/c4a784c2a197a4dabc59505aefc2d97965dc4188/aeidon/markups/ass.py#L45

I believe this is correct SSA vs. ASS -wise as per [ass-specs.doc](http://moodub.free.fr/video/ass-specs.doc).
