### ISSUE TITLE
Videos can be loaded, but they are black even though the sound is played.

### ISSUE THREAD

**Issue by insciwetrust** [otsaloma/gaupol#126]
![image](https://user-images.githubusercontent.com/48178408/54044137-3e491480-41df-11e9-95ed-1da800e9ec00.png)

**Comment by otsaloma** [comment]
You're probably missing some GStreamer plugins that provide needed codecs. Which of bad, good, ugly, libav do you have installed?

**Comment by insciwetrust** [comment]
I wasn't able to load any video before, I made a research and installed "gstreamer1.0-gtk3" using "apt-get install" command. That's when I was able to load videos but this time I encountered this. I am kind of a newbie to Linux, how do I check and install the missing plugins?

**Comment by otsaloma** [comment]
A couple things.

1. If you install Gaupol via your distro's package management, `apt-get install gaupol` as you seem seem to be using Debian/Ubuntu or something similar, then you should automatically get the right dependencies, at least usually.

2. If you need to install dependencies manually (and maybe Gaupol as well), the command is at the bottom of the README, see <https://github.com/otsaloma/gaupol>, scroll to the bottom.

3. If that doesn't work, you can try the [Flatpak](https://flathub.org/apps/details/io.otsaloma.gaupol). You need to [setup](https://flatpak.org/setup/) some stuff if you haven't used Flatpak/Flathub before. That Flatpak has all dependencies including codecs bundled, it should "just work" regardless of which distro you're using.

**Comment by insciwetrust** [comment]
I am indeed using a Debian based distro, I installed Gaupol through snap. 

I manually installed the dependencies by the way, and you were right, some of them were missing, seemingly. Everything works fine now, thank you a lot for your help!

**Comment by insciwetrust** [comment]
I am indeed using a Debian based distro, I installed Gaupol through snap.

I manually installed the dependencies by the way, and you were right, some of them were missing, seemingly. Everything works fine now, thank you a lot for your help!
