### ISSUE TITLE
"Open recent" also shows recent text files from user account in Linux Mint

### ISSUE THREAD

**Issue by nohamelin** [otsaloma/gaupol#132]
Hi Osmo,

Running gaupol built from the latest source code, commit 63c06bc: the "open recent" menu can shows files not opened by gaupol too; these are plain text files recently open by the OS, including, by example, bash scripts, though no pdf or other complex types.

Rebuilding after changing HEAD to commit e3ae7c61 doesn't show this behaviour.

System: Linux Mint 19.1 Tessa, Xfce desktop.

Commands used to build and run each time:

    python3 setup.py clean
    mkdir -p locale/es/LC_MESSAGES
    msgfmt -cv --check-accelerators=_ po/es.po -o locale/es/LC_MESSAGES/gaupol.mo
    python3 setup.py install_data -d /tmp/gaupol
    python3 bin/gaupol

**Comment by otsaloma** [comment]
Thanks for noticing, it seems only one filter can be active at a time, we need  a custom filter here. I'll fix it.

**Comment by nohamelin** [comment]
I gave a try and it seems OK now. Regards.
