### ISSUE TITLE
Video speed playback.

### ISSUE THREAD

**Issue by 4fury** [otsaloma/gaupol#133]
How to? I tried write "mpv --speed=0.5" to other command or mpv config. No success.

**Comment by otsaloma** [comment]
Maybe you are confusing the internal and external video players? The internal video player uses GStreamer and has no option to set playback speed. Adding `--speed=0.5` should work as expected for the external mpv player launched via Tools / Preview or via the rightmost toolbar icon.

**Comment by 4fury** [comment]
Thanks. I see it. But why need an external video player?

If user react slowly? He can open mpv with speed value of "0.5" and vim, for example. Why need a gaupol?
