### ISSUE TITLE
Windows 10 / 64 - Errors after closing the preview

### ISSUE THREAD

**Issue by eurobank** [otsaloma/gaupol#135]
The error after shifting and preview. 

Traceback

File: C:\Users\osa\Desktop\gaupol-1.3.1\gaupol\agents\preview.py
Line: 36
In: _check_process_state

File: C:\Users\osa\Desktop\gaupol-1.3.1\gaupol\agents\preview.py
Line: 43
In: _handle_output

File: c:\python\32-bit\3.4\lib\encodings\cp1253.py
Line: 23
In: decode

UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 75: character maps to <undefined>

Environment

Platform: Windows-10-10.0.17763
Locale: el_GR.cp1253

Versions

aeidon: 1.3.1
chardet: 2.3.0
enchant: None
gaupol: 1.3.1
gstreamer: None
gtk+: 3.18.9
pygobject: 3.24.1
python: 3.4.4

**Comment by otsaloma** [comment]
Likely fixed now, but note that I don't know when or if I'll update the Windows installer, so this might not be of much use for you. Also, for what it's worth, your traceback likely implies that the video player failed, if it had worked, you would likely not have seen this dialog, so it's not just Gaupol. You could likely work around this issue, but I don't have Windows at hand, so can't help you there.

**Comment by eurobank** [comment]
Thanks for the help. Using your information above, i found that VLC was the problem (somehow) and switching to Custom and mpc-hc player worked just fine.

Pitty you are not sure if you do a Windows build anymore.
