### ISSUE TITLE
Can i turn off word count in subtitle? it quite anoying.

### ISSUE THREAD

**Issue by thanhtv-aivy** [otsaloma/gaupol#138]
i know this place is for issue but i don't know where to ask, so..
i don't want to display word count (image). please show me how.
https://pasteboard.co/Iw2qtTV.png

**Comment by otsaloma** [comment]
In the preferences dialog, see Edit / Preferences from the menubar.

![Screenshot from 2019-09-05 21-45-03](https://user-images.githubusercontent.com/237265/64370189-9cd43b80-d026-11e9-85b4-5e526cd76359.png)
