### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by meetdilip** [otsaloma/gaupol#139]
I was customizing my icons for Ubuntu and ended up making one for Gaupol as well. If you are interested, I don't mind if you use it for the project.

![subtitle editor](https://user-images.githubusercontent.com/6965443/65061654-0560d800-d998-11e9-99c3-902ccb51f2d5.png)

**Comment by otsaloma** [comment]
Thanks, but the icon was just refreshed for the latest release, 1.7, see #119. I'm not an icon artist and it's not perfect, but I do want to stay with the current symbology and the current style prevalent in GNOME.

**Comment by meetdilip** [comment]
This one, right ? Looks nice :)

https://github.com/otsaloma/gaupol/blob/master/data/icons/io.otsaloma.gaupol.svg

**Comment by meetdilip** [comment]
I know this is a closed issue. Just a  friendly share :)

![Gaupol-icon-size](https://user-images.githubusercontent.com/6965443/65402359-7581ba80-ddeb-11e9-99df-282c0f44050c.png)
