### ISSUE TITLE
"Cancel" button when exiting Gaupol with an unsaved document

### ISSUE THREAD

**Issue by aaaxx** [otsaloma/gaupol#14]
Version 0.24.3 for Windows.

When there's an unsaved document and you try to quit the app, you're offered to "Close Without Saving", "Cancel" or "Save" the document. However, "Cancel" does the same as "Close Without Saving" instead of cancelling the operation, which is what I would expect.

**Comment by otsaloma** [comment]
I see this in the latest version as well. Only happens if you hit the close button on the window, not when closing a tab (Ctrl+W) or quitting (Ctrl+Q).

**Comment by otsaloma** [comment]
Fixed in the howdoi development branch. Issue will probably be closed when I merge the branch into master.
