### ISSUE TITLE
Split doesn't work

### ISSUE THREAD

**Issue by Extarys** [otsaloma/gaupol#141]
- Create a new project
- Import video
- Paste lyrics into the first subtitle (No. 1)
- Select the line
- Press S (or right-click, click Split)

A new, empty subtitle appear below it (No. 2) with no text.

It should split the current selection in half (like gnome-subtitles)

Or maybe I'm doing this wrong? There is no way I'll manually create 250 lines :)

Version 1.7 under Mint

**Comment by otsaloma** [comment]
That's not really what the split functionality is for.

If you have a text file with 250 lines, one per subtitle, two possiblities come to mind.

1. Do a search-replace to turn the text file into a valid subtitle file, e.g. by doing a regex search-replace substituting `^` (beginning of line) with `00:00:00:` (zero timestamp) thus making it a valid [TMPlayer](https://github.com/otsaloma/gaupol/blob/master/data/samples/tmplayer.txt) file.

Or

2. In, Gaupol create a new project, insert 250 new subtitles. Then move focus to the text column of the first subtitle (but don't edit!) and hit Ctrl+V (Text / Paste from the menu). For this to work, subtitles need to be separated by blank lines in the pasted text – that's the syntax for this kind of text import/export considering subtitles can and do include linebreaks.

**Comment by Extarys** [comment]
I see. The second solution should work.

Thanks for explaining this to me.
