### ISSUE TITLE
Fonts really *NEED* to be adjustable in size

### ISSUE THREAD

**Issue by Davpruett** [otsaloma/gaupol#142]
First, congratulations on an excellent app: it is simple, intuitive, looks nice, and works very well.

Unfortunately, I work in Chinese==>English translation, and the simple fact is that the Chinese words as displayed by Gaupol are just too tiny for my eyes to read. I *NEED* to be able to make them bigger, and I cannot.

Thus, I cannot use Gaupol to do my translation work--and I find that extremely sad, because I like the program so much.

Please, on your next release, PLEASE include some means of adjusting the size of the displayed words. Currently, the size of displayed Chinese on a large computer screen is entirely too small to be legible.

Again: congratulations on an otherwise brilliant app. I look forward to using it again in the future.

**Comment by otsaloma** [comment]
Do the font settings in the preferences dialog not work for you? You should already be able to customize the font, including size, of both the editor font and the subtitle font of the integrated video player.

**Comment by Davpruett** [comment]
Ah! 

Thank you! I thought it was strange that I couldn't adjust the fonts--i just wasn't able to find where to adjust them. I went to the Text box, and also to the Preferences box, but the tab where "fonts" are adjusted is labeled as "Editor", and honestly I just glossed past the "Fonts" entry as I was searching for the function.

Just BTW--I also have done *many* searches for "Gaupol" "Help" and have come up with nothing. It might be good to add a page to Github, or on a Wiki somewhere, so that users can create solutions to these sorts of questions.

In my case, it was simply assuming that the "Editor" tab was for adjusting for things like cross-platform issues, when in fact I just didn't see the thing I needed to see because I was expecting the "Fonts" adjustment to be under the "Text" tab.

My mistake; my stupid; but yeah, a Wiki or contributable webpage somewhere would be useful to both you and the rest of us.

**Comment by otsaloma** [comment]
I think the tab structure of the preferences dialog is somewhat a problem. I have been planning to switch to a sidebar as that would allow e.g. Fonts to be its own top-level section, which is difficult with tabs as it grows the width of the dialog. GtkStackSidebar is the more modern solution compared to tabs and seems to work well in other apps.

https://developer.gnome.org/gtk3/stable/GtkStackSidebar.html

I'll close this issue. I'll do that sidebar eventually. Documentation I haven't wanted to write much as it's a lot of work to maintain it and not many users who actually read documentation. The little documentation that exists is accessible from the Help menu. It doesn't seem to show up in Google search results though, maybe I'll do something about that too, eventually.

https://github.com/otsaloma/gaupol/tree/master/doc
