### ISSUE TITLE
capitalisation

### ISSUE THREAD

**Issue by ubone** [otsaloma/gaupol#150]
text > case > sentence
works only for the first sentence
it should work with more than one sentences too

**Comment by ubone** [comment]
it would be nice to add it to the toolbar too

**Comment by otsaloma** [comment]
It's very non-trivial and language dependent to detect where sentences start. I don't want to add that there. The text correction assistant is the heavier tool that does that kind of stuff.

Regarding the toolbar, I'd say no. It's just not a common feature. It is though a feature that doesn't make much sense to be behind a complicated menu hierarchy as it's probably easier to just manually fix the capitalization, at least in a single subtitle, than mouse all the way over there. Keybindings would be an option, but it's hard to find good keys too and setting custom keybindings is too hard.

**Comment by ubone** [comment]
> It's very non-trivial and language dependent to detect where sentences start.

Just cap the word after a dot?

> it's probably easier to just manually fix the capitalization

then why have the option at all
