### ISSUE TITLE
Follow cursor

### ISSUE THREAD

**Issue by ubone** [otsaloma/gaupol#151]
> Issue

Text within a cell is not visible if it's long enough to not fit in the application's window.

> Proposal

Move (rotate) text with the cursor one character at a time when it reaches the window border.

**Comment by ubone** [comment]
This is when editing.

**Comment by otsaloma** [comment]
That's not really reasonably doable as the text editor is anchored to the cell view which scroll-bar'd into the window. Also, the rendering of the editor has been somewhat erratic in different GTK versions, so it's better to keep the placement code simple.

Also, it's difficult to see this as a common issue considering how much text you can fit on any regular desktop screen at 12pt (or whatever) compared how much can (or should) put in a subtitle.

**Comment by ubone** [comment]
eh no biggie. i figure i can copy into leafpad
