### ISSUE TITLE
Unknown bug

### ISSUE THREAD

**Issue by mlk71075** [otsaloma/gaupol#152]
It happened when I opened 2 different files i 1 window - seems each pane did what I wanted in other file: deleted (in file B) 2 highlited lines in file A. Traseback below was generated while closing 1 of them.

Regards,
HTH

Traceback

File: /usr/share/gaupol/gaupol/page.py
Line: 131
In: <lambda>

    request_close = lambda x, self: self.emit("close-request")

File: /usr/lib/python3/dist-packages/aeidon/observable.py
Line: 129
In: emit

    method(*((self,) + args + data))

File: /usr/lib/python3/dist-packages/aeidon/deco.py
Line: 218
In: inner_wrapper

    return function(*args, **kwargs)

File: /usr/share/gaupol/gaupol/agents/close.py
Line: 118
In: _on_page_close_request

    self.close(page)

File: /usr/share/gaupol/gaupol/agents/close.py
Line: 43
In: close

    self.update_gui()

File: /usr/share/gaupol/gaupol/agents/update.py
Line: 133
In: update_gui

    self._update_widgets(page)

File: /usr/share/gaupol/gaupol/agents/update.py
Line: 141
In: _update_widgets

    self.notebook.set_menu_label_text(

TypeError: Argument 1 does not allow None as a value

Environment

Platform: Linux-5.4.0-21-generic-x86_64-with-glibc2.29
Locale: pl_PL.utf_8

Versions

aeidon: 1.7
chardet: 3.0.4
gaupol: 1.7
gspell: 1
gstreamer: 1.16.2.0
gtk+: 3.24.17
pygobject: 3.36.0
python: 3.8.2

**Comment by otsaloma** [comment]
Sounds weird.

**Comment by mlk71075** [comment]
I've been using Gaupol for a while and never ever saw this before. I'm
running the latest Ubuntu and did something like now (many file at once)
already with some series/seasons. So I was surprised seeing this.
Unfortunately I cannot recreate the bug, can only tell you the traceback is
real.

I still miss 1 feature you withdrawn from the program which is a reverse
sequence of HTML markups. When I put in a mpl file /{font color}text I get
</i></font> in srt. I consider this a bug, a huge one in fact - a player
like mpv doesn't handle this correctly when I put more markups like {font
size}text{font color}  etc. Your program translates these in an order it
sees theme not in the reverse order and I have to do it manually.

Thanks.

pon., 13 kwi 2020 o 15:10 Osmo Salomaa <notifications@github.com>
napisał(a):

**Comment by otsaloma** [comment]
OK, I'll close this. I don't doubt that you ran into this issue, I don't doubt that the traceback is real. But, if neither of us can reproduce it and there's no clear description of the issue, it doesn't really help us.

Regarding the MPL markup issue, I don't recall this, I don't understand what has been withdrawn. Please open a separate issue with a one subtitle example of how Gaupol converts it and what you'd expect and why.
