### ISSUE TITLE
[Feature Request] Extracting hardcoded subs

### ISSUE THREAD

**Issue by Dnkhatri** [otsaloma/gaupol#159]
Would you be interested in adding this feature. A python project that does is already available gaupol calling it and importing the results would be good enough.

https://github.com/apm1467/videocr

**Comment by otsaloma** [comment]
Regarding OCR, I would be open to adding conversion of VobSub or BluRay SUP via Tesseract, but converting hard-coded subs from video frames sounds like a very rare, very slow, very niche thing to do. It probably makes more sense to do something like that at the command line.
