### ISSUE TITLE
Won't show NTFS drives

### ISSUE THREAD

**Issue by HalvorRaknes** [otsaloma/gaupol#160]
All other apps and the file utility shows all drives, including my Windows drives (NTFS), but Gaupol won't. Thus I have to "open the file in Gaupol" rather than open the file FROM Gaupol. But then, I can't open the video!

**Comment by otsaloma** [comment]
Please be more specific: Are you using Linux? Which distro? How did you install Gaupol? Are the drives mounted in a local path (such as `/mnt/drive1` or `/media/drive1`) or do you use them as some kind of network drives (such as `smb://...`)?

**Comment by HalvorRaknes** [comment]
I am using Linux Mint. I think I installed Gaupol from the mintinstall app in the systems menu.

Kernel: 5.3.0-53-generic x86_64 bits: 64 compiler: gcc v: 7.5.0 
           Desktop: MATE 1.22.2 wm: marco dm: LightDM Distro: Linux Mint 19.3 Tricia 
           base: Ubuntu 18.04 bionic 

i'm not sure about the way the drives are mounted. If you can give me some command I'll check.

**Comment by otsaloma** [comment]
> i'm not sure about the way the drives are mounted. If you can give me some command I'll check.

Can you post a screenshot of the open file dialog from a different app where you see the NTFS drive? You seem to be using the MATE desktop, The Pluma Text Editor would be a good app to check, since it uses the same toolkit as Gaupol. Is the drive in the sidebar or how do you access it? In the open dialog, you can also right-click a file under the NTFS drive and choose "Copy Location". When you paste that somwhere, you should see whether it's a local file (starts with `/`) or a network file (starts with `smb://`, `nfs://` or something).

**Comment by HalvorRaknes** [comment]
Rather than me having to install another text editor, does this work?![Skjermbilde på 2020-05-23 23-12-01](https://user-images.githubusercontent.com/65785947/82740627-fc0be480-9d4a-11ea-920f-07b062bd474a.png)

Compare with Gaupol.
![Skjermbilde på 2020-05-23 23-15-00](https://user-images.githubusercontent.com/65785947/82740663-4db46f00-9d4b-11ea-98a9-be7b1028f042.png)

**Comment by otsaloma** [comment]
Yes, thank you, that helps. That's a network drive. By default, the open file dialog shows only local files and that's what we have in Gaupol, just the plain default. It's quite a significant complication at this point to support network URIs and many parts of the code assume we're dealing with local filenames, so I don't expect that to happen.

I would suggest you work around this by using mounted local file paths. Some information [suggests](https://askubuntu.com/a/1224012) that those network locations are behind the scenes mounted at `/run/user/1000/gvfs/`. You can check if you find the files there. If you do, you can bookmark the location and it should work fine in Gaupol. There are also commands which you can use to explicitly mount the NTFS drive somewhere else, but if needed, you can ask some MATE forums (or Ubuntu or something) about that.

**Comment by HalvorRaknes** [comment]
Thank you!

I'll consider how I shall go on considering your response!
