### ISSUE TITLE
[New Feature Request] More frame rate

### ISSUE THREAD

**Issue by RafaMartorell** [otsaloma/gaupol#164]
Congratulations on this magnificent application.
I think that frame rates according to the new HD formats should be included.
The speed of 30, 50 and 60 frames per second is required.
There are already many videos that use these frame rates.
Thank you very much.

**Comment by otsaloma** [comment]
Can you please provide some link where these are listed along with where they are used and what is the exact value. I'm not really up-to-date on this myself and I'll gladly add any framerates as long as I can confirm that  they are indeed real, correct and relevant.

Also, if you need this yourself already now, you can use the custom framerates extension. See the extensions tab in the preferences dialog.

**Comment by RafaMartorell** [comment]
First of all, thank you very much.
On this website, 2016 explains very clearly the new frame rates in the era of HD video
https://www.borrowlenses.com/blog/intro-to-video-frame-rates-and-frames-per-second-shooting-speeds/
Also on Wikipedia you can see the new speeds, but I think that reaching 60 is enough for the vast majority of users working in HD
https://en.wikipedia.org/wiki/Frame_rate
You can also consult the Handbrake documentation and see that this application allows us to work with:
23,976 / 24 for film
25/50 for European broadcast standards
29.97 / 59.94 or 30/60 for North American broadcast standards.
https://handbrake.fr/docs/en/latest/technical/frame-rates.html
Greetings and if you need more documentation on the frame rates at present I can search the net.

**Comment by RafaMartorell** [comment]
Thank you very much, I have used the extension to define the new frame rates and it was perfect.
My most sincere congratulations on this magnificent application.

**Comment by otsaloma** [comment]
Thanks, I think I'll add 30, 50, 59.94 and 60.

**Comment by RafaMartorell** [comment]
Thanks to you. Good choice, they are frame rates that are used very often today.
