### ISSUE TITLE
Save changes to the text after mouse click

### ISSUE THREAD

**Issue by HydeFromT70s** [otsaloma/gaupol#166]
Hi.

Found this app today and just want to say it's great! A good subtitle editing application was missing under Linux. So thank you.

Now, to save changes to the text after editing it, the only way to do it is to hit Enter, which is not so intuitive and is annoying when you editing many lines.

Can you make changes to the text be saved when you click the mouse somewhere else in the app? It would be more intuitive and efficient.

**Comment by otsaloma** [comment]
Clicking outside explicitly triggers cancel and to my knowledge that's what it should do as it's consistent with other apps, and possibly some GTK defaults. If you use GNOME, you try can e.g. to rename a file in Nautilus (the file browser) and click outside (not the Rename button). Before Nautilus had the current popover, it had similar in-place editing as Gaupol. There should be other examples, but Nautilus is the only one that comes to mind right now.

**Comment by otsaloma** [comment]
Excel, LibreOffice Calc etc. are though good examples of the opposite, so I'm not sure about this, but would like to be consistent with GTK/GNOME.

**Comment by otsaloma** [comment]
Not going to change this, no clear reason to do so.
