### ISSUE TITLE
Thank you very much for the program!

### ISSUE THREAD

**Issue by mrkaban** [otsaloma/gaupol#168]
Hello, thank you very much for a good program under a free open source license! Added a program to a Russian-language site about free software, here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D0%BC%D1%83%D0%BB%D1%8C%D1%82%D0%B8%D0%BC%D0%B5%D0%B4%D0%B8%D0%B0/%D0%BF%D1%80%D0%BE%D1%87%D0%B5%D0%B5/gaupol-%D1%80%D0%B5%D0%B4%D0%B0%D0%BA%D1%82%D0%BE%D1%80-%D1%82%D0%B5%D0%BA%D1%81%D1%82%D0%BE%D0%B2%D1%8B%D1%85-%D1%84%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2-%D1%81%D1%83%D0%B1%D1%82%D0%B8%D1%82%D1%80%D0%BE%D0%B2.html).

The project is interesting, so please don't abandon it!

There will be no more assemblies for Windows?

**Comment by otsaloma** [comment]
> There will be no more assemblies for Windows?

I don't currently have interest in building Windows installers, but it's of course possible for someone else to pick it up or if tooling improves I could do them again, who knows.
