### ISSUE TITLE
Gaupol on chromebook

### ISSUE THREAD

**Issue by adonae** [otsaloma/gaupol#169]
Hello,

I'm really looking forward to using gaupol on my chromebook. I enabled the linux option on the chromebook and installed gaupol via deb file and the terminal, but in none of these ways did it work. Simply install it but when you open the program the screen goes black and the chromebook "restarts".

Would there be a way to use gaupol on the chromebook?

I apologize for the bad English, I'm Brazilian and I'm using the Google translator.

**Comment by otsaloma** [comment]
I'm not familiar with Chromebook, so I can't help much there.

The only thing that come to mind, is that you could try the Flatpak.

https://flatpak.org/setup/Chrome%20OS/

https://flathub.org/apps/details/io.otsaloma.gaupol

**Comment by adonae** [comment]
Thanks a lot for the help! I followed these steps and they worked.
