### ISSUE TITLE
Restore speech recognition

### ISSUE THREAD

**Issue by otsaloma** [otsaloma/gaupol#17]
PocketSphinx has been ported to GStreamer 1.0.

http://cmusphinx.sourceforge.net/wiki/gstreamer

Previous discussion: https://bugzilla.gnome.org/show_bug.cgi?id=757743

**Comment by otsaloma** [comment]
Another speech recognition system to keep an eye on.

* http://chrislord.net/index.php/2017/02/23/machine-learning-speech-recognition/
* https://github.com/mozilla/DeepSpeech

**Comment by meetdilip** [comment]
Are you planning to auto-create subtitles from the audio ?

**Comment by otsaloma** [comment]
It's an interesting possibility, but not under active development.

A previous of Gaupol had support for speech recognition via CMU pocketsphinx, but that was disabled due to library incompatibilities. It would now be possible to restore it, but it was never really good and there are better alternatives now, maybe not quite ready, but at least under development. Also, it might be possible to use some Amazon/Google/etc APIs, but that has it's own problems as well.

**Comment by meetdilip** [comment]
It would be great to have such a feature. I hope some day that will come to Gaupol.  Is there any other service I can use locally to auto-generate videos ? Thanks.

**Comment by otsaloma** [comment]
There are at least some web services and some scripts that use various APIs, but I haven't tested them so I don't know if they are any good and I can't recomment anything in particular.

**Comment by otsaloma** [comment]
Based on Mozilla's DeepSpeech:

https://github.com/abhirooptalasila/AutoSub

Just tried it, it's alot better than PocketSphinx ever was, but still far from being usable without heavy manual editing afterwards.

It's beginning to become clear that the state of the art in this matter is in various command line programs with very heavy dependencies and either poor or non-existent packaging, which basically means I'm very unlikely to integrate any of this into Gaupol. Thus, closing this issue.
