### ISSUE TITLE
aeidon package status

### ISSUE THREAD

**Issue by nijel** [otsaloma/gaupol#170]
As a maintainer of [translate-toolkit](https://github.com/translate/translate/), I'd like to know status of the [aeidon package](https://pypi.org/project/aeidon/). 

The current PyPI package seems to be uploaded by @jrabbit from https://github.com/jrabbit/gaupol, but that one doesn't have an issue tracker enabled and is fork of this repo. Is there some intention to maintain this package?

What brought me here is problem in the package - it fails to parse most of the formats because it doesn't ship the data it uses when parsing the files, see https://github.com/translate/translate/issues/4155#issuecomment-717056777

**Comment by otsaloma** [comment]
Hi! When long ago splitting the aeidon package from the codebase and making it separately installable, unfortunately, it didn't occur to me to upload it to PyPI. Also, unfortunately, it occured to someone else who apparently thought that Gaupol's setup.py was too complicated and wanted to simplify it. The breakage you see is the result of that simplification, the package just simply doesn't include the necessary data files.

I haven't tried to take over the PyPI package, I don't know what the process for that would be or if there's risk of some kind of breakage for users. I would be willing to maintain it though. From my perspective, currently, the codebase is maintained, but I cannot recommend using the PyPI package.

**Comment by otsaloma** [comment]
Maybe I could, at least for now, upload it PyPI under a different name, would that work for you?

**Comment by nijel** [comment]
> From my perspective, currently, the codebase is maintained, but I cannot recommend using the PyPI package.

For most of Python users that is the way to install, so I'd really prefer to get that into good shape.

> Maybe I could, at least for now, upload it PyPI under a different name, would that work for you?

I would not mind, changing the dependency is not that big deal for us. On the other side it would be certainly better to take over existing package and maintain that. Also, the situation is not that urgent - the breakage is there for months and this is first time somebody noticed.

Hopefully, @jrabbit will be willing to add you as a maintainer there. In case we won't get response from him, there is [process for taking over the package](https://www.python.org/dev/peps/pep-0541/#how-to-request-a-name-transfer).

**Comment by otsaloma** [comment]
> Also, the situation is not that urgent

Looks like I should probably switch from distutils to setuptools, so it'll take a while.

**Comment by jrabbit** [comment]
I'm able to add you, what is the pypi user you have?

**Comment by otsaloma** [comment]
It's otsaloma there as well: https://pypi.org/user/otsaloma/

**Comment by jrabbit** [comment]
Ok, I sent an invitation for you to also be an owner of the package on pypi.

**Comment by otsaloma** [comment]
Thanks. No one else, just me.

**Comment by nijel** [comment]
Is there something where you would like to get some help? There is another issue with the published aeidon package - it requires `chardet<4.0`, so it is not compatible with current chardet release.

**Comment by otsaloma** [comment]
I first thought I'd migrate the whole setup.py to setuptools, which looked like a big thing. Now I think I'll just add a separate setup.py for the aeidon PyPI package. That should be easier and I'll get it done soon. I can do the bigger migration later.

Regarding chardet, where did you get that aeidon needs < 4.0? I haven't tested 4.0 yet, but I don't see any relevant API changes. But, I can check it, it should be very easy to make it work with both 3 and 4 if needed.

**Comment by nijel** [comment]
It's in the existing package on PyPI - from https://github.com/jrabbit/gaupol/blob/8389c6ceaaac8e809af8925fe6ffb9f67890b161/pyproject.toml#L14

**Comment by otsaloma** [comment]
OK, I'll check it and fix for the PyPI package. I have always marked chardet version dependency as "any", since I don't remember the API having ever changed: https://github.com/otsaloma/gaupol/blob/master/README.md#source

**Comment by jrabbit** [comment]
setup.py and setuptools are the same system/thing???? what are you all
talking about?

**Comment by otsaloma** [comment]
The Gaupol codebase is 15 years old. Python has had an annoying amount of all kinds of new packaging formats, tools and websites over the years. Back when I started [distutils](https://docs.python.org/3/library/distutils.html) was the official, right thing to use. Now it seems deprecated. It works fine as far as I can tell, if you just execute the script yourself, but PyPI documentation doesn't mention distutils, only setuptools, so I can't tell if I can push whatever distutils produces to PyPI.

And it might be that it's easy to switch, perhaps just changing `from distutils... import ...` to `from setuptools... import ...`, but I need to look through it carefully, since Gaupol is packaged in many distros and I don't want to break things.

**Comment by nijel** [comment]
Yes, that's all you will need to change. Setuptools are built on top of distutils.

**Comment by otsaloma** [comment]
Should be done now. I'll fix some other little bugs and make a new release before uploading to PyPI, probably in the next couple days.

And I checked chardet 4, it works fine.

**Comment by otsaloma** [comment]
It's out now. Let me know if any problems remain.

**Comment by nijel** [comment]
Thanks, it seems to work fine in my tests!
