### ISSUE TITLE
Gaupol runs stat() on all recent files, even those that are filtered out

### ISSUE THREAD

**Issue by sbraz** [otsaloma/gaupol#175]
Hi,
I noticed that gaupol is sometimes slow to start and tracing it shows that it is running `stat()` on all files listed under `~/.local/share/recently-used.xbel`. This is especially problematic when network mounts are used: if one mount containing a recent file hangs, I'm unable to start Gaupol.

The problem is that `stat()` is called for each file before the custom filter is called:
https://github.com/otsaloma/gaupol/blob/de5b81565b5a145eb07613a081211c3677d347da/gaupol/agents/menu.py#L52

I don't know if there is a way to avoid this when using `RecentChooserMenu`, I searched for a bit but could not find any info or relevant issues for pygobject or GTK.

**Comment by otsaloma** [comment]
Maybe you could try flipping this line:

https://github.com/otsaloma/gaupol/blob/de5b81565b5a145eb07613a081211c3677d347da/gaupol/agents/menu.py#L47

As far as I can tell `recently-used.xbel` should contain information needed to do the filtering, so maybe the disk use is just checking if the file exists?

**Comment by sbraz** [comment]
@otsaloma good guess! Omitting the parameter or setting it to `True` fixes this :)
I guess existence could be verified after the application and mime types have been checked.

**Comment by sbraz** [comment]
Apparently the filter doesn't expose the URI, even when I add `Gtk.RecentFilterFlags.URI` to flags. This means that filtering out non-existent files should be done manually (and that we can't use `menu.set_limit(10)` any more).

**Comment by otsaloma** [comment]
I don't really see a way around this apart from heavy custom code instead of `Gtk.RecentChooser` (which I don't want to do) or some hidden preference to toggle the check.

I also checked gedit for comparison, they list all recent files whether they exist or not. It's possible to do that as well. I personally though like to move files around, for videos a sort of unseen/seen folder separation and would find it annoying to see obsolete files in those lists.

**Comment by sbraz** [comment]
Do you know why the `URI` flag for the filter doesn't seem to work? Maybe I should open an issue about this upstream?

I understand that you don't want to write custom code. If there is no way to fix the filter, would you consider adding an option to disable `set_show_not_found`?

**Comment by otsaloma** [comment]
I don't know why URI doesn't work. I tested it too yesterday and it was all None.

I'll add a hidden preference.

**Comment by otsaloma** [comment]
Done now. If with this change you start and quit Gaupol once, it'll write into the config file

    [recent]
    # show_not_found = false

Then you can just flip and uncomment it.

**Comment by sbraz** [comment]
Thanks, I will set that :smiley:.

Did you see that `GtkRecentChooser` has been removed from GTK 3.24.19?
GNOME/gtk@55874470ff6d619dd05d8c344d4b3c3205982eae and https://gitlab.gnome.org/GNOME/gtk/-/issues/2514

This means that you will have to get rid of it sooner or later, right?

I have attempted to list recent files without it and it was really easy but I guess the annoying part is displaying the menu itself, like `Gtk.RecentChooser` did?

In case you want to see what I have done:
```py
import aeidon
import gi
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk


manager = Gtk.RecentManager.get_default()
recent_items = []
for item in manager.get_items():
    application = "gaupol" in item.get_applications()
    mime_type = item.get_mime_type() in [x.mime_type for x in aeidon.formats]
    if application and mime_type and item.exists():
        recent_items.append(item)
        if len(recent_items) == 10:
            break
print(recent_items)
```

I wouldn't mind trying to do the rest of the work and replacing the actual menu with it if you're interested in a PR. Please let me know.

**Comment by otsaloma** [comment]
It's probably *deprecated* in GTK3 and no longer in GTK4. I haven't yet looked into GTK4, but yes, there are probably a lot of deprecations.

Now that I look, there seems to be a bunch of menu and toolbar deprecations too, so there's no point rewriting anything using those deprecated menus. I think it makes sense to do these in one go, a bit later.

https://developer.gnome.org/gtk4/stable/ch41s02.html#id-1.7.4.4.71

**Comment by sbraz** [comment]
I don't really understand how GTK versions work, why is the removal commit part of v3.24.19?

**Comment by otsaloma** [comment]
I don't remember exactly either, since they are just switching to the new versioning scheme, but I think it's just that those late 3.x are basically alpha, beta or rc versions of 4. There should be no removals within stable releases of 3, just deprecations.

**Comment by otsaloma** [comment]
That 3.24.19 probably isn't correct, I have 3.24.24 and Gaupol works fine.
