### ISSUE TITLE
Check spelling & Find and  Change error

### ISSUE THREAD

**Issue by mlk71075** [otsaloma/gaupol#186]
Hello,

Was working on a series of 10 subs: (MPL2) in 1 window.  Nothing fancy here, right? Just spell checking (lots of errors on these subs) and changing pattern of "/" into "/{\c&H77ccbb&}" to save it later into ASS format. This change of formats is done outside of Gaupol in a little proggie i wrote based on an example from aegis' docs.
Hope what I wrote is clear. Back to an issue: while changing patterns i got a message the change was done, but didn't see it in the subtitles! So I ttried again, with same result.and again without seeing the change in the susbtitles' lines. The change was seen however in the change dialog window, so I undid 2 unnesessary changes, saved the subs ond wanted to clese them, while was given this very error.

This did not have any impact on 3 other instances of Gaupol I had opened. Also closing the subtitles went normal w/o affecting those 2 still untouched from the series (number 9 and 10).

The importance of this issue is none, I also don't know if I can recreate it. Unfortunatelly it was not possible to do anything in this very window - another error box appeared and I had to shut it down.

**Comment by otsaloma** [comment]
I don't really understand what happened there, but

* If you see the "Something went wrong" dialog, it would help to copy-paste the text from there
* The "Something went wrong" is basically an unhandled error, some things might work after that, but it's better to quit and restart after taking note of the error
* Other (smaller) error dialogs are lesser issues
* Gaupol is not a single instance app, so different windows are separate processes and thus independent
