### ISSUE TITLE
Empty lines remain after correction

### ISSUE THREAD

**Issue by mlk71075** [otsaloma/gaupol#187]
Hello,

Ubuntu Impish (21.10)
Gaupol 1.9-1
Aeidon 1.9-1

Tools/Correct Texts/Remove empty lines checked.
Zero empty lines removed

**Comment by otsaloma** [comment]
It only removes subtitles that are blank _after_ corrections, so primarily it's intended for use when removing hearing impaired subtitles, if e.g. everything between `[...]` is removed and there's nothing else left, then the whole subtitle will be removed as well.

There isn't currently a feature to remove blank subtitles otherwise, it hasn't been a common issue to my knowledge.

**Comment by mlk71075** [comment]
OK, thanks for explanation.
I had an out of sync subfile which I used as translation in Gaupol. After
just opening these subtitles they became synced, at least they look like
so. However I got many empty lines as a buy product. Seems I just need to
use grep and/or other Linux tools to get rid of them.
Or maybe you can point me a way to do it with aeidon lib. Unfortunately I
don’t program in Python, but I know how to make a proggie in it.



W dniu niedz., 8.08.2021 o 15:44 Osmo Salomaa ***@***.***>
napisał(a):

**Comment by otsaloma** [comment]
One way to do it would be to first do a search-replace in Gaupol: Search for `\A\Z` and replace with `[]`. `\A\Z` is basically a regular expression for a blank string. You need to check the "Regular expression" box in the dialog. Then you can use the correct texts feature to remove hearing impaired stuff between square brackets and resulting empty subtitles will be removed as well. This will work as long as there are no brackets used elsewhere.

And, generally speaking, the reason why I say is that it's not a common issue is that blank subtitles don't usually do any harm. Playback should work fine, you can leave them in the file. But, if they somehow bother when editing or something, try the above.

**Comment by mlk71075** [comment]
Thanks again, you're very helpful.
I used grep cause it WAS easy. I wanted to know how many of these lines
were, so i did:
***@***.***:~$ grep ",,$" $s | wc -l
367
These are ASS subtitles. Now I use only.this format, which I find much more
flexible than SRT. I just had to modify /usr/share/gaupol/headers/ass file
to my needs

Kind regards Osmo,
Marek

niedz., 8 sie 2021 o 16:58 Osmo Salomaa ***@***.***>
napisał(a):
