### ISSUE TITLE
hover cursor to resize layout

### ISSUE THREAD

**Issue by milahu** [otsaloma/gaupol#193]
i can resize the internal video player when i click-and-drag below the seek bar

i expect the hover cursor (mouse pointer symbol) to change to: ⬍ Up Down Black Arrow

**Comment by otsaloma** [comment]
I do get the correct cursor, on GNOME with the default Adwaita cursor theme. I think this is very directly related to GTK and cursor theme, not Gaupol specifically. What distro and cursor theme do you have?

**Comment by milahu** [comment]
aah, sorry, my bad. seems i had no cursor theme
