### ISSUE TITLE
Unable to load any video

### ISSUE THREAD

**Issue by csosog** [otsaloma/gaupol#195]
I installed gaupol on a win7 machine. 
Following the tuto (https://github.com/otsaloma/gaupol/blob/master/doc/creating-subtitles.md), I ckick on {file} and {new}, it's OK.
When I click on {video}, I can't click on anything. Why ?

**Comment by otsaloma** [comment]
The Windows version never had the builtin video player, see e.g. https://github.com/otsaloma/gaupol/issues/190#issuecomment-944999766

I'll update the README to reflect that.
