### ISSUE TITLE
How can I delete this program?

### ISSUE THREAD

**Issue by zhurx01** [otsaloma/gaupol#197]
Thanks to the author of gaupol

I have a problem, now I don't need this program, how do I remove it?

**Comment by otsaloma** [comment]
There's no uninstall command as that would be problematic to implement, but the names "gaupol" and "aeidon" should be unique and thus easy to just list the files and delete. If you installed to `/usr/local`, you can list the installed files e.g. using find at the command line.

    find /usr/local -iname "*gaupol*"
    find /usr/local -iname "*aeidon*"
