### ISSUE TITLE
[Feature request] Edit SRT from video file

### ISSUE THREAD

**Issue by KaKi87** [otsaloma/gaupol#200]
Hello,

It would be nice to read and edit subtitles embedded in video files like MKV and MP4.

Thanks

**Comment by otsaloma** [comment]
I do agree that existing tooling is bad -- I personally use custom scripts to run mkvextract, then edit, and don't mux back in, instead I have configured mpv to prefer external subtitles -- but I don't really want to expand the scope of Gaupol to muxing and demuxing, which are quite different from the current model of being essentially a text editor.
