### ISSUE TITLE
Gdk.Cursor constructor returned NULL

### ISSUE THREAD

**Issue by eliseuschmidt** [otsaloma/gaupol#202]
Traceback

File: /app/lib/python3.9/site-packages/gaupol/agents/open.py
Line: 194
In: _on_notebook_drag_data_received

    self.open_main(subtitles)

File: /app/lib/python3.9/site-packages/aeidon/deco.py
Line: 218
In: inner_wrapper

    return function(*args, **kwargs)

File: /app/lib/python3.9/site-packages/gaupol/agents/open.py
Line: 269
In: open_main

    gaupol.util.set_cursor_busy(self.window)

File: /app/lib/python3.9/site-packages/gaupol/util.py
Line: 339
In: set_cursor_busy

    cursor = Gdk.Cursor.new_for_display(

TypeError: constructor returned NULL

Environment

Platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.33
Locale: pt_BR.utf_8

Versions

aeidon: 1.11
chardet: 3.0.4
gaupol: 1.11
gspell: 1
gstreamer: 1.18.6.0
gtk+: 3.24.35
pygobject: 3.42.2
python: 3.9.9

**Comment by otsaloma** [comment]
I guess you're using Wayland? (seems I should add that to the "Environment" info above)

Looks like a clear issue, I'll fix it soon

* https://gitlab.gnome.org/GNOME/meld/-/issues/724
* https://github.com/matplotlib/matplotlib/issues/19405

**Comment by otsaloma** [comment]
OK, it should be fixed now, but still wondering if this is Wayland or what and which distro? If Gaupol is broken for all Wayland users, I'd better make a release...

**Comment by eliseuschmidt** [comment]
Wayland.
Distro: Ubuntu 22.04.
But is app Flatppak.

**Comment by otsaloma** [comment]
Thanks. Maybe I'll make a release just in case. I suspect there's something more about the environment that triggers this as I'd expect there to be a lot of Wayland users by now and I haven't seen this issue before. I'm still on X, but I've tried Gaupol on Wayland and fixed all the issues I saw already years ago.
