### ISSUE TITLE
Enable conversion to sentence case under Correct Texts

### ISSUE THREAD

**Issue by plrao72** [otsaloma/gaupol#203]
It's currently possible to change the text case for individual subtitle files to sentence case but the option is not available under Correct Texts. It would be great if this could be included.

**Comment by otsaloma** [comment]
You should be able to select all subtitles (with focus being in the Text column, indicated by the italic header) and then do the case conversion to change all.

I don't think this belongs in Correct Texts as it doesn't usually give a good result and so differs from the rest of corrections that make minimal beneficial changes.

For what it's worth, what I usually do if I have bad subs in this sense (usually all upper case), I first convert to all lower case as mentioned above and then use "Capitalize texts" in the "Corrects Texts" wizard. That usually gives a reasonable result – names, abbreviations etc. will remain wrong – running spell-check might help correct those if willing to manually go through them.
