### ISSUE TITLE
Multiple file at once crashes

### ISSUE THREAD

**Issue by mlk71075** [otsaloma/gaupol#207]
This bug is permanent - I often open bunch of subtitles at once. At first everything looks OK, but later while editing 1 of panes gets "empty title" and some otther pane gets it's title doubled - just like the one empty goes to the other. Then gaupol crashes, often upon writing changes to a disk.

**Comment by mlk71075** [comment]
EDIT: It's editing what makes the error - when I open some files but edit just one at a time it's all OK provided I save & close the file.

**Comment by otsaloma** [comment]
Sounds really weird, I don't remember seeing anything like this before. I too often open multiple subtitle files at once and have done so for years. If you can reproduce the issue, screenshots or a screen recording would help me understand.

**Comment by mlk71075** [comment]
OK, it's not Gaupol then. I guess you don't use Ubuntu like I do.
Thanks.

czw., 11 maj 2023 o 00:42 Osmo Salomaa ***@***.***>
napisał(a):

**Comment by otsaloma** [comment]
OK, closing, but can reopen if needed.
