### ISSUE TITLE
Maybe a typo in ui text

### ISSUE THREAD

**Issue by tzwasd** [otsaloma/gaupol#209]
Can't find the word "parantheses" in [dictionary.com](https://www.dictionary.com/misspelling?term=parantheses) and [dictionary.cambridge.org](https://dictionary.cambridge.org/us/spellcheck/english/?q=parantheses), Maybe the standard and correct spelling is "parentheses"?

**Comment by otsaloma** [comment]
Yeah, it's a typo, probably replicated using auto-complete. I'll fix it.
