### ISSUE TITLE
Fields in gaupol/enums.py never be translated

### ISSUE THREAD

**Issue by tzwasd** [otsaloma/gaupol#210]
These string fields can't be tanslated for anyway.

(1) Screenshot from main window:
![Screenshot_20230525_222906](https://github.com/otsaloma/gaupol/assets/68690643/0cc206e0-96d2-430e-9392-02dd2e0e635c)
(2) Screenshot from preference window:
![Screenshot_20230525_223027](https://github.com/otsaloma/gaupol/assets/68690643/76fbf7db-7475-4909-9eca-aafc0b345ee8)

**Comment by otsaloma** [comment]
Are you sure? Those are marked as translatable and are extracted to the POT and PO files.

https://github.com/otsaloma/gaupol/blob/master/gaupol/enums.py#L81-L85

I seem to have some locale trouble on my system, I can't test myself right now.

**Comment by otsaloma** [comment]
Sorry, this might be some kind of an import order issue. Maybe I have changed the import order at some point and broken this. I'll test once I have my system back in shape.

**Comment by otsaloma** [comment]
I confirm now, this has probably been broken a long time. I don't know anymore what I had originally thought about how this should work. I think I need to add some lazy gettext wrappers for the enums.
