### ISSUE TITLE
Update Windows packaging

### ISSUE THREAD

**Issue by otsaloma** [otsaloma/gaupol#23]
MSYS and WiX?

https://git.gnome.org/browse/gedit/tree/win32/make-gedit-installer

**Comment by otsaloma** [comment]
MSYS seems interesting, but is missing at least PyWin32. WiX and gedit's installer script are probably not useful for a Python application.

I updated the old Windows packaging scripts that use the pygi-aio bundle. In general, PyPI/PIP have made things easier and GTK+ 3.18 seems good enough that I can finally consider a new 0.91 installer stable and replace the old 0.19.1. It's likely that there are some Windows-specific bugs, but those can be fixed with time.

GStreamer (the built-in video player) still doesn't work. See separate bug #27 about that.

If someone is reading, you can try the below installer. Let me know if there are problems. Otherwise, the actual release (0.91) will follow in maybe a week or so.

https://dl.dropboxusercontent.com/u/39625783/gaupol-0.90.20160708-win32.exe

**Comment by sergeevabc** [comment]
Err… Hello? The latest Windows version available in this repo is 1.3.1 dated Nov 12, 2017. Could you be so kind to update it?
