### ISSUE TITLE
Non-Latin encoding didn't recognized.

### ISSUE THREAD

**Issue by Achaean** [otsaloma/gaupol#232]
Gaupol don't any more recognize non-Unicode SRTs and I can't find any option to change to ISO-something.

PS. OK! I found it.
Auto-detection, messing things up.
For things to work out, it has to be disabled.

**Comment by otsaloma** [comment]
We changed the auto-detection library in #222. It should be better now, but it's also possible there are some regressions. As you probably noticed, you can configure a list of fallback encodings in the preferences dialog and disable auto-detection if needed.

**Comment by Achaean** [comment]
Yeah!
I didn't noticed ti at the 1st place, but this is an auto-detection bug, not Gaupol's.

I corrected the report's title, so now it isn't a misnomer.  :-)
