### ISSUE TITLE
All actions enabled after subtitle cell editing cancelled

### ISSUE THREAD

**Issue by nohamelin** [otsaloma/gaupol#30]
Hi,
Giving a try to the current gaupol from git in a live session of Fedora 24 Workstation:

* Open gaupol and create a new document. Note that the "Preview in external video player" button in the main ~~menu~~ toolbar is disabled, as it's expected.
* Click to edit the text of the unique subtitle created by default. NO add any text to it. Click outside of it to close the edition mode.
* Now the Preview button is found enabled. Clicking in it triggers an error:

> File: /home/liveuser/Descargas/gaupol-0.91/gaupol/agents/preview.py
> Line: 63
> In: _on_preview_activate
> 
>     self.preview(page, position, doc)
> 
> File: /home/liveuser/Descargas/gaupol-0.91/gaupol/agents/preview.py
> Line: 73
> In: preview
> 
>     position, doc, command, offset, encoding, temp)
> 
> File: /home/liveuser/Descargas/gaupol-0.91/aeidon/agents/preview.py
> Line: 123
> In: preview
> 
>     VIDEOFILE=aeidon.util.shell_quote(self.video_path))
> 
> File: /home/liveuser/Descargas/gaupol-0.91/aeidon/util.py
> Line: 407
> In: shell_quote
> 
>     path = path.replace("\\", "\\\\")
> 
> AttributeError: 'NoneType' object has no attribute 'replace'
> 
> Environment
> 
> Platform: Linux-4.5.5-300.fc24.i686-i686-with-fedora-24-Twenty_Four
> Locale: es_ES.utf_8
> 
> Versions
> 
> aeidon: 0.91
> chardet: 2.2.1
> enchant: 1.6.6
> gaupol: 0.91
> gstreamer: 1.8.1.0
> gtk+: 3.20.6
> pygobject: 3.20.1
> python: 3.5.1

**Comment by otsaloma** [comment]
I can't reproduce this.

And looking at the code, it does specifically check that `video_path` is not `None`.

```python
class PreviewAction(gaupol.Action):
    ...
    def _affirm_doable(self, application, page, selected_rows):
        aeidon.util.affirm(page is not None)
        aeidon.util.affirm(page.project.video_path is not None)
        if gaupol.conf.preview.use_custom_command:
            aeidon.util.affirm(gaupol.conf.preview.custom_command)
```

https://github.com/otsaloma/gaupol/blob/master/gaupol/actions/tools.py#L71

**Comment by nohamelin** [comment]
The first step should refers to the Preview button in the main toolbar, not the main menu.

**Comment by otsaloma** [comment]
> The first step should refers to the Preview button in the main toolbar, not the main menu.

The menubar item and toolbar item states should match as they're both connected to the same action and the state information comes from the action. Do they match?

**Comment by nohamelin** [comment]
I update the reproducing steps in the first comment: the real steps were more specific than what I said before; sorry about that.

**Comment by nohamelin** [comment]
And yeah, I check now and both the menuitem and the button are always in sync.

**Comment by otsaloma** [comment]
Thanks, now I see it. Not just preview, but almost all actions are enabled.

Most of the actions are disabled when editing, because the keybindings conflict with text editing. It seems that if editing is cancelled (clicked outside subtitle rows or Escape pressed) the action states are not updated. I'll fix it.
