### ISSUE TITLE
Possibility of changing italics format

### ISSUE THREAD

**Issue by lisuml** [otsaloma/gaupol#33]
It's very common in subtitles that italics are forwarded by '/' character instead of '{Y:i}' sequence. It would be nice to have possibility of transform from one notation to the other, maybe in text correction tool?

**Comment by otsaloma** [comment]
Are you referring to the MPL2 format?

Normally one file format has only one valid markup format. When you save a file in a different format, Gaupol will convert the markup. MPL2 is an exception as it allows both native markup (`/` at the beginning of line for italics) as well all markup of the MicroDVD format (`{Y:i}` and `{y:i}` for italics).

**Comment by lisuml** [comment]
Ok, that explains a lot. Thanks!
