### ISSUE TITLE
Display applied fixes in "Correct Texts"

### ISSUE THREAD

**Issue by sbraz** [otsaloma/gaupol#35]
It would be nice to have an option to show what fixes were applied to each line (especially when we want to disable them because they are false positives). Maybe this could be shown when hovering over the line?
I haven't looked at the code so I don't know if it's easily doable, maybe you don't check which fixes cause changes.

**Comment by otsaloma** [comment]
I understand this could be marginally useful in debugging, but I'm afraid it sounds too complicated both code- and especially UI-wise and I assume also not of much use for most users. I try to keep false positives to a minimum and hopefully normal users shouldn't run into difficult-to-identify corrections.
