### ISSUE TITLE
Break lines on dialogues is not working in 0.92

### ISSUE THREAD

**Issue by lisuml** [otsaloma/gaupol#36]
For example:

`- Dialogue1. - Dialogue2.`

should be corrected to:

```
- Dialogue1.
- Dialogue2.
```

But it does not work currently.

**Comment by otsaloma** [comment]
Works for me. Do you perhaps have the skip options checked? With the default values, lines considered good are skipped and everything that's not overlong is considered good. Trying to figure out if a non-overlong line is bad would probably result in a lot of false positives -- dialogue is a good example as dashes are used for many other things too, which should not cause a line break.

![opts](https://cloud.githubusercontent.com/assets/237265/18617560/1039fb88-7ddb-11e6-87a1-abbf9d4bebd4.png)

**Comment by lisuml** [comment]
Yes, that did the trick. Thanks!
