### ISSUE TITLE
Error trying to undo more of the possible actions done

### ISSUE THREAD

**Issue by nohamelin** [otsaloma/gaupol#38]
With Gaupol 0.92:
* Open a big subtitle file (1 hour or longer).
* Do an expensive action (e.g. change framerates).
* Press quickly Ctrl+Z multiple times to undo the action.

While the application is trying to undo the action done (it takes 1-2 seconds here), the second undo request seems be registered too, triggering the following error:

> Traceback
> 
> File: /usr/lib/python3.5/site-packages/gaupol/agents/edit.py
> Line: 310
> In: _on_undo_action_activate
> 
>     self.undo()
> 
> File: /usr/lib/python3.5/site-packages/gaupol/agents/edit.py
> Line: 395
> In: undo
> 
>     page.project.undo(count)
> 
> File: /usr/lib/python3.5/site-packages/aeidon/agents/register.py
> Line: 199
> In: undo
> 
>     return self._revert_multiple(count, aeidon.registers.UNDO)
> 
> File: /usr/lib/python3.5/site-packages/aeidon/agents/register.py
> Line: 167
> In: _revert_multiple
> 
>     self._do_description = stack[0].description
> 
> IndexError: list index out of range
> 
> Environment
> 
> Platform: Linux-4.7.6-200.fc24.i686+PAE-i686-with-fedora-24-Twenty_Four
> Locale: es_ES.utf_8
> 
> Versions
> 
> aeidon: 0.92
> chardet: 2.2.1
> enchant: 1.6.6
> gaupol: 0.92
> gstreamer: 1.8.3.0
> gtk+: 3.20.9
> pygobject: 3.20.1
> python: 3.5.1

**Comment by otsaloma** [comment]
I can reproduce it. I've seen this before and twice done something that I thought fixed it, but I seem to have only tested small actions that were fast to undo. I'll look into it.

**Comment by nohamelin** [comment]
Yeah, I remember seeing it occasionally in the times of... uh, Gaupol 0.19, maybe. On the other hand, it is the first time that I see it with more recent releases.

**Comment by nohamelin** [comment]
I tried the master build with this fix; it's working fine, as far as I could test it.

**Comment by otsaloma** [comment]
Good to hear. Thanks for testing.
