### ISSUE TITLE
LRC support

### ISSUE THREAD

**Issue by cweiske** [otsaloma/gaupol#39]
It would be nice if gaupol would support .lrc files which are often used for music.

https://en.wikipedia.org/wiki/LRC_(file_format)

**Comment by otsaloma** [comment]
It doesn't seem difficult, but seems a bit obscure for a subtitle editor. Maybe I'll find the time to add it, but no promises, no ETA. I'd also accept a pull request if someone wants to get it done sooner.

**Comment by cweiske** [comment]
I'd like to use gaupol to create music lyric files, and LRC would fit best.
