### ISSUE TITLE
No video preview on elementary OS

### ISSUE THREAD

**Issue by Pemicope** [otsaloma/gaupol#42]
Hello, thank you for this great subtitle editor!

I'm just having an issue with it on elementary OS. Everything is working fine except the video preview.
I can hear the sound but there's no video on the application itself. But if I preview it on MPlayer I have sound and image. I've also tried it on Linux Mint and still no video. It works fine on GNOME and Kubuntu though... Do I need to install something else to make work?

Thank you and keep up the great work!

**Comment by otsaloma** [comment]
Do you mean Gaupol's integrated video player (from the menubar: Video / Load Video etc.) or the external video player (Tools / Preview)?

**Comment by Pemicope** [comment]
Yes, the integrated video player is not working properly. I hear only sound, no image. The preview with external player is working fine. Thank you for your reply.

**Comment by otsaloma** [comment]
Two things you can try.

1. Start Gaupol from a terminal and see if you get any error output there.

2. Try playing the same video in another GStreamer-based video player, e.g. Totem and see if that works. If you need to install another video player, also try Gaupol again after that in case it installed some missing dependencies.

**Comment by Pemicope** [comment]
I started Gaupol from the terminal and got the following error messages:

/usr/share/gaupol/gaupol/__init__.py:58: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
/usr/share/gaupol/gaupol/player.py:30: PyGIWarning: GstPbutils was imported without specifying a version first. Use gi.require_version('GstPbutils', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import GstPbutils

I had Totem installed and the videos play fine there, or any other video player, just not on Gaupol.
Thank you!

**Comment by otsaloma** [comment]
No information there, those warnings are not serious. More questions.

1. Which version of Gaupol are you using? Check from the menubar Help / About.

2. Are you by any chance using Wayland or Mir? If you don't know, you probably aren't.

3. Do you have all of the following packages installed? (It's the list of dependencies of the latest Debian package. If Elementary is based on Ubuntu and Ubuntu on Debian, it should probably apply to your case as well.)

```
Depends: python3,
         python3-aeidon,
         python3-gi,
         python3-gi-cairo,
         gir1.2-gtk-3.0,
         gir1.2-glib-2.0,
         gir1.2-gstreamer-1.0,
         gir1.2-gst-plugins-base-1.0,
         gstreamer1.0-plugins-good
Recommends: python3-enchant,
            python3-chardet,
            gir1.2-gtkspell3-3.0,
            gstreamer1.0-plugins-bad,
            gstreamer1.0-plugins-ugly,
            gstreamer1.0-libav
```

**Comment by Pemicope** [comment]
1. I'm using the latest version, 1.0

2. No, I don't think I'm using any of those. Unless it comes pre-installed with elementary. I just installed the OS and did some updates.

3. Yes, I have all those installed.

Thank you for your support.

**Comment by otsaloma** [comment]
> I'm using the latest version, 1.0

That doesn't add up. The output error messages you posted earlier shouldn't happen with 1.0. Do you have multiple versions installed? You can try e.g. `which -a gaupol` at a terminal. How did you install?

**Comment by Pemicope** [comment]
Yes I find is strange too, it always worked fine on Ubuntu. Now I've been trying other distros and it's not working.

The output I get is ``/usr/bin/gaupol``

As far as I know I have only one version installed; the latest.

I've always installed it this way: download the file, extract and inside I ran the following command:
``sudo python3 setup.py clean install``

This always worked for me, except now on elementary. So, I installed the version from the AppCenter first, version 0.28.2, to check if it worked as before. Still no video. So, I installed the latest version on top of this one. I also re-installed elementary and installed just the latest Gaupol version. Everything is working but the video.

Thank you!

**Comment by otsaloma** [comment]
You should never install software manually to `/usr`, which is where the package manager installs software. You might end up with a mixture of different versions or some conflicts as distros can have some special handling of Python code to facilitate Python upgrades and recompilation.

Instead, you should install manually to `/usr/local` using

```
sudo python3 setup.py install --prefix=/usr/local
```

`clean` isn't needed anymore, but does no harm. At least on my system, if you don't give the `--prefix`, `setup.py` does the right thing and defaults to `/usr/local`. Maybe for some reason this is different on Elementary and you have to be explicit?

> I also re-installed elementary and installed just the latest Gaupol version.

If this is your current situation, you have made the above mistake, but if you have not had Gaupol installed via package management, it should not have done any harm yet. Two more things come to mind you could try.

1. Install anew to `/usr/local`.

2. In the unpacked Gaupol source directory try running the command `tools/play VIDEO`, where `VIDEO` is the full path to a video file. That runs a simplified, stand-alone version of Gaupol's integrated video player, leaving out potential problems with the rest of Gaupol.

**Comment by Pemicope** [comment]
I didn't know that! Always learning. :)

I removed Gaupol and re-installed it as you instructed to ``/usr/local`` but still no video.
I also ran the command ``tools/play VIDEO`` and still the same.
I probably messed something up before. I'll re-install elementary, update and install Gaupol using the command ``sudo python3 setup.py install --prefix=/usr/local``.
If it still doesn't work I'll just install a different distro, no problem.

Thank you so much for your help! 👍

**Comment by Pemicope** [comment]
I installed elementary and updated the system. Next I installed Gaupol with the following command ``sudo python3 setup.py install --prefix=/usr/local``. I opened Gaupol and everything seems to be working. Next I opened a subtitles file, all good. But when I open the video file I get the following message, as you can see on this screenshot.
![shot](https://cloud.githubusercontent.com/assets/8180278/22046761/ddd05c4c-dd1a-11e6-910f-5323456a2edb.png)

I'm guessing something is missing on elementary? It's fine, I'll just use another distro, there's plenty to choose from. :)

Thank you for your time and support!

**Comment by otsaloma** [comment]
GstPbutils is included in package `gir1.2-gst-plugins-base-1.0`.

If you're switching distros, I'll close this issue, but do post again if you run into problems on another distro.

**Comment by Pemicope** [comment]
Yes, thank you so much for your support.
