### ISSUE TITLE
Please add support for webvtt

### ISSUE THREAD

**Issue by rbrito** [otsaloma/gaupol#46]
Hi.

Some devices, like the high-profile [chromecasts][0], can support subtitles, but only in a format called [WebVTT][1]. The format is based on `srt` and a simple conversion can be achieved by using something like:

    ffmpeg -i input.srt output.vtt

It would be superb if gaupol supported WebVTT out-of-the-box, even if not in its full generality, since this is one of the formats that we can expect other software/hardware to support and gain adoption, due to the [W3 Consortium][2] formalizing it.

Thanks for maintaining gaupol as one excellent subtitle editor,

Rogério.

P.S.: Subtitles served via Youtube already are downloaded in WebVTT and youtube-dl converts them to srt via ffmpeg, an external tool.

[0]: https://developers.google.com/cast/docs/media
[1]: https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API
[2]: https://w3c.github.io/webvtt/

**Comment by otsaloma** [comment]
I had not heard of WebVTT before, but it sure sounds important.

There is some weird stuff indeed like comments and cue identifiers, editing of which won't be supported, but I think I should be able to preserve them as-is, so that opening a file and saving it would not destroy anything.

I should probably manage to do this sometime in the near term.

**Comment by rbrito** [comment]
Dear @otsaloma, first of all, thank you very much for the quick response.

Regarding WebVTT, I think that a basic support would be super nice to have, even if the support doesn't come with all the bells and whistles.

Thank you very much,

Rogério.

**Comment by otsaloma** [comment]
Basic support for WebVTT is done.

* Comments and styles are not editable, but should be preserved in most cases. They are attached to the following subtitle and thus preserved as long as that subtitle is not removed.

* Both time formats (`HH:MM:SS.SSS` and `MM:SS.SSS`) are supported. When saving a file, the shorter format is used if the total length is less than an hour, else the longer format.

* Any other blocks than the header, styles, comments and cue (identifier, time, settings, text) is silently ignored and not preserved upon open + save.

* Bold, italic and underline markup is converted when converting to another format, all other markup tags are discarded.

Feel free to test. I'll make a new release maybe in a week or so.
