### ISSUE TITLE
sh: update-desktop-database: command not found, failed in installation on Mac OS X EI Capitan

### ISSUE THREAD

**Issue by tianqig** [otsaloma/gaupol#48]
Tried to install gaupol on my iMac by the following come:
$ python3 setup.py install
during running install_egg_info, got the following error message:

**sh: update-desktop-database: command not found**
command 'update-desktop-database "/Users/xxx/anaconda/envs/py3/share/applications"' failed

Please help, thanks

**Comment by otsaloma** [comment]
That is a warning, not an error. `update-desktop-database` probably doesn't do anything useful on macOS or Windows and it doesn't matter if it fails. It's the last thing in the installation process, so if that's the only thing that failed, the installation probably was successful.

Please note that even though the installation might have succeeded, I have never heard of anyone running Gaupol on macOS. It most likely does not work "out of the box".
