### ISSUE TITLE
Add option to remove exact duplicate subtitles

### ISSUE THREAD

**Issue by rbrito** [otsaloma/gaupol#51]
Hi.

First of all, thank you for adding the support for WebVTT to gaupol. It is really appreciated.

I would like to request a feature that would make gaupol nice to remove some subtitles that are exact duplicates with everything like start time, end time, duration (of course) and text.

In my experience, these are present when the original is malformed and, to get the files tidy, I would like to eliminate such problematic captions.

I'm attaching a file with such a problem here. (Sorry that I had to put a txt extension or github wouldn't allow me to upload the file).

Thanks for this creating amazing tool,

Rogério.

[greys-anatomy-s13e07.srt.txt](https://github.com/otsaloma/gaupol/files/1099402/greys-anatomy-s13e07.srt.txt)

**Comment by otsaloma** [comment]
Hi,

I don't see duplicate subs as being a common problem. When something is malformed, it can be malformed in many different ways. In your case, it seems if you open the file with a text editor and delete anything from line 4915 (after subtitle 1142) onwards, the file should be fine. For some reason there's junk in the end.

So, I don't expect to add this kind stuff to the GUI, but if you're comfortable with the command line and maybe Python, you can use the aeidon package (part of Gaupol) to do this kind of cleaning. As an example, a script to remove duplicate subs is in the below gist.

https://gist.github.com/otsaloma/0e54c27ef061c636cf9d338ad058da7d

Unfortunately the API documentation for aeidon is currently offline. It was at gna.org and I received no notification that they shut down. I'll move it somewhere else soon.

**Comment by rbrito** [comment]
Dear Osmo,

On Sat, Jun 24, 2017 at 11:36 AM, Osmo Salomaa <notifications@github.com> wrote:
> I don't see duplicate subs as being a common problem. When something is malformed, it can be malformed in many different ways.

Oh, sure. In a myriad of ways, I completely understand that. My point
is that I've seen this particular problem with gaupol generating
multiple lines more than once, but I never bothered submitting a
problem, since the number of duplicates was small and I deleted them
manually. It was only now that I decided that other people could be
seeing this particular problem that I saw that it, perhaps, could be
useful for me and for other users.

But I surely understand your point, being also a maintainer of a
semi-popular program in Python (https://github.com/coursera-dl).

> In your case, it seems if you open the file with a text editor and delete anything from line 4915 (after subtitle 1142) onwards, the file should be fine. For some reason there's junk in the end.

Humm, I thought that that subtitle would be OK, since it contains
multiple lines (I don't know if there is a spec for srt files like
there is for WebVTT---sorry for my ignorance), and I get your point
about how TVs and settop boxes could get confused with that
"almost-timestamp" being there. Is that the problem? Or is the problem
the presence of multiple lines?

> So, I don't expect to add this kind stuff to the GUI, but if you're comfortable with the command line and maybe Python, you can use the aeidon package (part of Gaupol) to do this kind of cleaning. As an example, a script to remove duplicate subs is in the below gist.
>
> https://gist.github.com/otsaloma/0e54c27ef061c636cf9d338ad058da7d

Excellent! I will try that on the subtitle and see the results that I get.

Oh, BTW, I run a command called prospector (essentially, a code
quality analyzer for Python) and it found some minor issues that you
may, perhaps, want to fix. Some are just cosmetic, some are some
imports that may be unneeded.

If you want, I can try my first experiences sending a pull request for
gaupol, since I like it very much. The only problem is that I don't
really know anything related to gtk (read: "I fear programming with
gtk so, so much"). :-) But I can understand some basic Python.

> Unfortunately the API documentation for aeidon is currently offline. It was at gna.org and I received no notification that they shut down. I'll move it somewhere else soon.

Oh, I see. The best course of action would be to move the code/issues
to github (or other similar alternatives, but I see that you have no
problem with github) and put the documentation on readthedocs.


Thanks once again,

Rogério.

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

**Comment by otsaloma** [comment]
> Humm, I thought that that subtitle would be OK

It's probably syntactically OK, but clearly some kind of an error had happened to whoever made that subtitle file and in some cases those problems are easier to fix with a text editor before opening with Gaupol, as Gaupol will sort the subtitles upon opening and thus might "hide" the problems.

There's also a chance that some players will get confused if the subtitles are in the wrong order. And depending on where exactly that cut-off point for the extra junk was, there could be a possiblity of syntactical error or at least ambiguity.

> Oh, BTW, I run a command called prospector

If you understand Python enough to review the warnings given by prospector, then I'd like to see a pull request. If you can't review them, then no, as there are likely to be a lot of false positives.

I use pyflakes myself in normal development. I have previously, long ago, used pylint, but got tired of way too many complaints. As an example, "unneeded imports" are caught by pyflakes too and any cases that remain should all be false positives. Regarding style, I do follow PEP-8, but I don't want to be too dogmatic about it, I make exceptions at times, on purpose.

> The best course of action would be to move the code/issues to github and put the documentation on readthedocs

I have moved everything else away from gna.org already long ago, only the API documentation has remained. I'll probably put the API docs somewhere under otsaloma.io/gaupol (it's hosted on Amazon S3). readthedocs.org is the long term plan, but it needs changes to the build mechanism (#22).

**Comment by otsaloma** [comment]
API docs moved now: http://otsaloma.io/gaupol/doc/api/aeidon.html
