### ISSUE TITLE
Video player actions sensitive when playback initialization fails

### ISSUE THREAD

**Issue by Fornost461** [otsaloma/gaupol#52]
I only report this because an error message invited me to, the bug is not annoying to me.
Here is how I can make it happen:

1. GStreamer Libav plug-in must not be installed.
2. Load a `.srt` file.
3. Load a video for which gaupol requires the above plug-in. A message appears saying that a GStreamer plug-in is missing (“Failed to initialize playback”).
4. Select subtitles and press `O` (or select `Video` > `Play Selection` in the menu bar). An error message appears with the following information:

**Traceback**

File: /usr/lib/python3.6/site-packages/gaupol/agents/video.py
Line: 208
In: _on_play_selection_activate

    self.player.play_segment(start, end)

File: /usr/lib/python3.6/site-packages/gaupol/player.py
Line: 299
In: play_segment

    end = min(duration, self.calc.to_seconds(end)) * Gst.SECOND

**TypeError:** '<' not supported between instances of 'float' and 'NoneType'

**Environment**

Platform: Linux-4.11.9-1-ARCH-x86_64-with-arch
Locale: en_US.utf_8

**Versions**

aeidon: 1.2
chardet: 3.0.4
enchant: 1.6.8
gaupol: 1.2
gstreamer: 1.12.2.0
gtk+: 3.22.16
pygobject: 3.24.1
python: 3.6.1

**Comment by otsaloma** [comment]
Thanks, those actions should have been disabled, fixed now.
