### ISSUE TITLE
How to install gaupol on ubuntu 16.04

### ISSUE THREAD

**Issue by WPFilmmaker** [otsaloma/gaupol#55]
Hi @otsaloma first of all thanks for developing gaupol! I looked around in the subtitle editors for linux and gaupol seems to be the best (at the least of those I was able to run and whose version is not 2 years old).
 
I was able to run gaupol without installing it following the instruction in the readme.md. However when I try to install it (as per install.md) I am stuck. 

I use cd to enter gaupol folder and then I run:     python3 setup.py install [--prefix=...]

But I get: invalid command name '[--prefix=...]'

How do I solve that?

Thanks a lot!

**Comment by otsaloma** [comment]
In command line program documentation, brackets `[]` indicate optional arguments and in this case `...` as something for you to fill in. Most likely you want use

```bash
sudo python3 setup.py install --prefix=/usr/local
```

The default prefix, i.e. where the program is installed, might vary by distro -- usually it's either `/usr` or `/usr/local`. Usually, distro package managers install software under `/usr` and to avoid conflicts with that manual installs should be done under `/usr/local`.

**Comment by WPFilmmaker** [comment]
Thanks! I followed your command and I think and I am able to run gaupol 1.2 by clicking on the icon in /home/myusername/Gaupol-1.2/data :)

**Comment by otsaloma** [comment]
OK, good. You should also find the icon in Ubuntu's applications menu or Dash or whatever it is.
