### ISSUE TITLE
Requiring namespace 'Gst' version '0.10', but '1.0' is already loaded

### ISSUE THREAD

**Issue by WPFilmmaker** [otsaloma/gaupol#56]
Hi, when I try to load a video I get the error "Failed to initialize playblack: Requiring namespace 'Gst' version '0.10', but '1.0' is already loaded".

I am not an expert but from the message I think Gaupol requires an earlier version of gstreamer. Would you be able to update the dependency or..? How should I proceed?
WP

**Comment by otsaloma** [comment]
Gaupol uses GStreamer 1.0. I don't know why you get that error message or what it means, but you should at least check that you have the dependencies installed. Since you installed Gaupol manually, you'll need to install the dependencies manually. In one command:

```bash
sudo apt-get install \
    gir1.2-glib-2.0 \
    gir1.2-gst-plugins-base-1.0 \
    gir1.2-gstreamer-1.0 \
    gir1.2-gtk-3.0 \
    gstreamer1.0-plugins-good \
    python3 \
    python3-gi \
    python3-gi-cairo \
    gir1.2-gtkspell3-3.0 \
    gstreamer1.0-libav \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-ugly \
    python3-chardet \
    python3-enchant
```

**Comment by WPFilmmaker** [comment]
Thank you this fixed the issue! (you can close this ticket)
