### ISSUE TITLE
Time jumps make Gaupol freeze after audio track change

### ISSUE THREAD

**Issue by Fornost461** [otsaloma/gaupol#58]
### How I can make the bug happen:

1. Load subtitles.
2. Load a video having two soundtracks.
3. Pause it.
4. Switch to the other soundtrack.
5. Move the video's time cursor (either manually, or through an automated function, like `Seek …` or `Play Selection`, but not `Play/Pause`).

### Workaround:

Let the video play with the newly selected soundtrack before making a time jump. In other terms, either omit step 3, or unpause the video right after step 4. Note that one can then pause the video and make time jumps at will without the bug occurring, unless the sountrack is changed during a pause again.

**Comment by otsaloma** [comment]
Thanks, I confirm. I had seen this this before, but I didn't know how to reproduce it. Might be difficult to debug, I'll look into it when I have the time.

**Comment by otsaloma** [comment]
Thanks for the detailed bug report, I didn't find the source of the issue, but I adopted your work-around, I think it's good enough.
