### ISSUE TITLE
Load video by drag-and-drop

### ISSUE THREAD

**Issue by Fornost461** [otsaloma/gaupol#59]
When dragging and dropping a video file on Gaupol, it tells the user that the file seems too big to be a text-based subtitle file. I suggest asking the user to choose between loading the file as a video or as subtitles. (Edit: the issue also happens when passing a video file as an argument when launching Gaupol from the command line. The -v option does not solve the issue as it does not load the video in Gaupol's player.)

**Comment by aaaxx** [comment]
It would be better to skip the dialogue and just load it as video if the file has any of the supported video extensions.

**Comment by Fornost461** [comment]
Sure, I assumed that extension might not be enough to determine whether the file contained a video or subtitles.

**Comment by otsaloma** [comment]
Good idea. The detection can be done by Python's mimetypes module, checking for `video/*` mimetype and falling back on a list of filename extensions, as the mimetypes module doesn't work well on Windows. That detection code already exisits, just needs some refactoring to use it for drag and drop. I'll add this along with the next batch of fixes.

https://docs.python.org/3/library/mimetypes.html#mimetypes.guess_type

https://github.com/otsaloma/gaupol/blob/master/aeidon/agents/preview.py#L25
