### ISSUE TITLE
Internal video player doesn't work on Wayland

### ISSUE THREAD

**Issue by JiangHongTiao** [otsaloma/gaupol#60]
Hi guys,
I have downloaded subtitles&video from: https://www.youtube.com/watch?v=CeBHA2m8xm4
I have dragged and dropped automatically generated subtitles (srt) into the program. Then I have tried to load video, unfortunately app has crashed. Video is of the format.
I'm attaching bugreport and mediainfo information. Thank you for your work and time guys!

```
**Traceback**

File: /usr/lib/python3.6/site-packages/gaupol/agents/video.py
Line: 184
In: _on_load_video_activate

    self.player.set_path(path)

File: /usr/lib/python3.6/site-packages/gaupol/player.py
Line: 331
In: set_path

    self.set_uri(aeidon.util.path_to_uri(path))

File: /usr/lib/python3.6/site-packages/gaupol/player.py
Line: 340
In: set_uri

    self._xid = self.widget.get_window().get_xid()

AttributeError: 'GdkWaylandWindow' object has no attribute 'get_xid'

**Environment**

Platform: Linux-4.11.10-300.fc26.x86_64-x86_64-with-fedora-26-Twenty_Six
Locale: en_GB.utf_8

**Versions**

aeidon: 1.0
chardet: 2.3.0
enchant: 1.6.10
gaupol: 1.0
gstreamer: 1.12.2.0
gtk+: 3.22.17
pygobject: 3.24.1
python: 3.6.2
```

**Comment by otsaloma** [comment]
It seems you're running Wayland. I haven't yet tried Gaupol on Wayland myself, but it seems some changes are needed. I'll look into it when I have the time.

As a workaround, does launching Gaupol from a terminal with command `GDK_BACKEND=x11 gaupol` work?

**Comment by JiangHongTiao** [comment]
Hi Osmo,
thanks a lot for reply and pointing me out.
Yes, specifying gdk_backend Param has helped and the video is working now,
sending quick screenshot.
Good job!
Thanks for development and your time!
Juraj+


On Aug 3, 2017 19:11, "Osmo Salomaa" <notifications@github.com> wrote:

It seems you're running Wayland. I haven't yet tried Gaupol on Wayland
myself, but it seems some changes are needed. I'll look into it when I have
the time.

As a workaround, does launching Gaupol from a terminal with command
GDK_BACKEND=x11
gaupol work?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/otsaloma/gaupol/issues/60#issuecomment-320032282>, or mute
the thread

**Comment by JiangHongTiao** [comment]
Hi Osmo,
thanks a lot for reply and pointing me out.
Yes, specifying gdk_backend param has helped and the video is working now,
sending quick screenshot.
Good job!
Thanks for development and your time!
Juraj+

**Comment by otsaloma** [comment]
Could some good folks here running Wayland test the latest development version with the above potential fix? Just download, unpack and run `bin/gaupol`.

**Comment by JiangHongTiao** [comment]
Hi Osmo,
it works for me whithout problem. The only msg in the console is:
(python3:3265): Gtk-WARNING **: Allocating size to GtkApplicationWindow
0x55e6f653e2b0 without calling gtk_widget_get_preferred_width/height(). How
does the code know the size to allocate?

Here is at least my uname: Linux 4.13.10-200.fc26.x86_64 x86_64 x86_64
x86_64 GNU/Linux
and screenshot:

 [image: Inline images 1]

Thanks for your work!
Juraj+

**Comment by otsaloma** [comment]
Thanks, I think this is fixed now.

**Comment by aboofgggg** [comment]
Gaupol inside the software the video player isn't ticked in the view bar and also can not load ideos please help my system is a windows 7 64bit and no languages but everything else is working properly acceptb those
![gaupol 1](https://user-images.githubusercontent.com/47154653/51928575-8c0b7980-23f6-11e9-9370-3fd15c629e3f.jpg)
![gaupol 2](https://user-images.githubusercontent.com/47154653/51928576-8c0b7980-23f6-11e9-9f1e-e7b717daec82.jpg)
![gaupol 3](https://user-images.githubusercontent.com/47154653/51928578-8ca41000-23f6-11e9-9e86-33b071dc689b.jpg)
![gaupol 4](https://user-images.githubusercontent.com/47154653/51928580-8ca41000-23f6-11e9-8fa8-9ec927da2596.jpg)

help please
