### ISSUE TITLE
Installer blocked by Windows Defender in Widows 10 Creators Update

### ISSUE THREAD

**Issue by Lokotito** [otsaloma/gaupol#61]
The installer gaupol-1.2-win32.exe (downloaded from here) is blocked by win10 x64 creator update, says that may damage the pc.

**Comment by otsaloma** [comment]
I haven't yet installed that Creators Update and might not for some time. If someone has time too look into this and tell me what I should do differently with the installer (sign it or something?) I'd appreciate it.

To confirm, when you say the installer is blocked, does Windows Defender allow you to bypass it, i.e. is there some "install anyway" button?

**Comment by blogodorio** [comment]
Tive problemas em atualização direta e duas instalações limpas do Creators: não acessava internet, problema com driver defeituoso, dizia, sobre Intel PRO/Wireless 3945ABG, e houve falha em Mobile Intel 945 Express Chipset Family. Já havia desistido, depois de tentar centenas de tutoriais e instalações de fábrica. De repente, sem que eu esperasse, meu velhinho D520/2gb/32 bits atualizou a 15.063 e está rodando que é uma beleza eheh A atualização de meu driver de wi-fi é de 2010, orque a Intel não dá mais suporte...

**Comment by Lokotito** [comment]
otsaloma, no, deffender blocks the installations and can't continue.

**Comment by Tekki** [comment]
The reason is that the code is neither signed nor distributed through the Windows Store. Here you find an explanation and best practices: https://blogs.msdn.microsoft.com/ie/2012/08/14/microsoft-smartscreen-extended-validation-ev-code-signing-certificates/

**Comment by otsaloma** [comment]
Thanks, for the link. Solutions look complicated and/or expensive. It might be a while before I get around to fixing this. In the mean time, I suggest turning off whatever it is in Windows Defender that gives you a hard block.

**Comment by otsaloma** [comment]
Closing Windows-specific bugs. GTK+3 has never really taken off on Windows, it seems best to just forget about Windows-packaging and let these issues lie.
