### ISSUE TITLE
Gaupol icon is missing from alt+tab menu and dash under Gnome Wayland session

### ISSUE THREAD

**Issue by glaubersm** [otsaloma/gaupol#62]
Gnome 3.24.2 on Arch.

![alt tab menu](https://user-images.githubusercontent.com/15967631/29003472-afd42bc8-7a8d-11e7-8526-59210f441bd5.jpg)
![dash](https://user-images.githubusercontent.com/15967631/29003475-b49a264e-7a8d-11e7-88fb-0d57e05bc410.jpg)

**Comment by otsaloma** [comment]
I don't have Wayland at hand to test on. Is this a problem in Wayland and/or Wayland distros or in Gaupol? Any idea what I should change?

**Comment by glaubersm** [comment]
Some programs had/have the same bug

https://bugzilla.redhat.com/show_bug.cgi?id=1334915
https://bugzilla.gnome.org/show_bug.cgi?id=785611
https://bugs.kde.org/show_bug.cgi?id=382122
https://bugs.kde.org/show_bug.cgi?id=382353

I'm not a software dev, but I think it's a Gaupol bug.
Fedora 26 runs Wayland by default. You can check this bug on it.

**Comment by otsaloma** [comment]
An explanation of the issue: https://wiki.gnome.org/Projects/GnomeShell/ApplicationBased

**Comment by otsaloma** [comment]
Could you try the latest commit with a possible fix? You can just download the source, unpack and run `bin/gaupol`.

**Comment by glaubersm** [comment]
Just installed gaupol-git on Arch
https://aur.archlinux.org/packages/gaupol-git/

It's fixed! Thank you otsaloma!
