### ISSUE TITLE
Integration of a translation service

### ISSUE THREAD

**Issue by meetdilip** [otsaloma/gaupol#63]
Is it possible to use Google Translate or Bing Translate inside Gaupol ? Currently, we need to copy the content, translate it on a service interface and paste it back to subtitle. Is it possible to automate the whole process inside Gaupol ? ie, choose a language to automatically create a translation using one of those services.

**Comment by otsaloma** [comment]
Translation services could technically be added, but reasons of terms of use, usage quotas and pricing, and perhaps discouraging bad practices, I'm unlikely to want to provide that.

But, it is of course possible to automate such a task with a small Python script that uses Gaupol's [aeidon package](http://otsaloma.io/gaupol/doc/api/aeidon.html). Something like

```python
#!/usr/bin/env python3
import aeidon, sys, time

if len(sys.argv) < 2:
    print("Usage: {} SUBTITLE_FILE...".format(__file__))
    raise SystemExit(1)

def translate(text):
    # ADD TRANSLATION API CALL HERE.

for fname in sys.argv[1:]:
    print("{}:".format(fname))
    project = aeidon.Project()
    project.open_main(fname, "utf_8")
    for i in range(len(project.subtitles)):
        text = translate(project.subtitles[i].main_text)
        project.subtitles[i].main_text = text
    ext = project.main_file.format.extension
    project.main_file.path = project.main_file.path[:-len(ext)]
    project.main_file.path += ".{:.0f}{}".format(time.time(), ext)
    print(project.main_file.path)
    project.save_main()
```

At least Google Translate has a Python client, so it should be easy to add the actual API call.

* https://github.com/google/google-api-python-client
* https://github.com/google/google-api-python-client/tree/master/samples/translate

**Comment by meetdilip** [comment]
Thanks @otsaloma . Will it be possible to help me on how to use the above script with Gaupol for auto-translate using Google Translate. I am pretty new to Python and Gaupol.

**Comment by otsaloma** [comment]
The only thing that script is missing is the translation service part and I'm not the person to help you with that. If using a command line script and web API seems difficult, maybe you'll want to use something like Google's Translate Toolkit? With a couple clicks you get a fully translated SubRip file that you can then open and edit further in Gaupol.

https://www.ghacks.net/2015/03/16/translate-subtitles-quickly-with-googles-translator-toolkit/

**Comment by meetdilip** [comment]
Awesome ! Thanks. :)
