### ISSUE TITLE
Shift positions of all open projects.

### ISSUE THREAD

**Issue by khanhhung2512** [otsaloma/gaupol#66]
There's an option to "Shift positions of all open projects" in an older version of Gaupol. I wonder why it's missing in newer versions (0.91 and above).

**Comment by otsaloma** [comment]
It's very very rare to need to do an equal shift for multiple files. So, it was originally thoughtlessly included and removed later as unneeded noise. What's your use case, why do you need it?

**Comment by khanhhung2512** [comment]
Well, I watch a lot of TV series, and sometimes, the episodes have some advertising at the beginning. For a series, the advertising parts usually have the same length for all episodes. That's why "Shift positions of all open projects" is very useful to me.

**Comment by otsaloma** [comment]
I understand now that it could sometimes be useful, but I still think's it's such rare that I'm not going to accomodate, especially given that the dialog already has a choice of three targets, four would be a lot.

**Comment by p2635** [comment]
Is this open for reconsideration? The use case for me is a lot of poorly timed subtitles and I know all of them need to be shifted forward by 9 seconds. The problem is, I have to do it one by one.

**Comment by otsaloma** [comment]
All right, all right.

**Comment by p2635** [comment]
Thanks a hundred billion million @otsaloma , you are sugoi
