### ISSUE TITLE
playbin.query_position fails when loading video

### ISSUE THREAD

**Issue by luisjure** [otsaloma/gaupol#67]
Traceback

```
File: /usr/lib64/python3.5/site-packages/gaupol/agents/video.py
Line: 270
In: _on_seek_next_activate

    subtitles = list(filter(lambda x: x[0] > pos + 0.001, self._cache))

File: /usr/lib64/python3.5/site-packages/gaupol/agents/video.py
Line: 270
In: <lambda>

    subtitles = list(filter(lambda x: x[0] > pos + 0.001, self._cache))

TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'

Environment

Platform: Linux-4.13.10-gentoo-x86_64-Intel-R-_Core-TM-_i7-5820K_CPU_@_3.30GHz-with-gentoo-2.4.1
Locale: es_UY.utf_8
```

Versions

```
aeidon: 1.2
chardet: 3.0.4
enchant: 1.6.8
gaupol: 1.2
gstreamer: 1.12.3.0
gtk+: 3.22.19
pygobject: 3.24.1
python: 3.5.4
```

**Comment by otsaloma** [comment]
This is likely some kind of a codec issue. Did you install with the Gentoo ebuild? Which GStreamer plugins do you have installed?

**Comment by luisjure** [comment]
Hi,
yes, I installed from the ebuild, and I also suspected the gst-plugins. I wouldn't be able to spot where the problem might be, there are more than 30 plugins installed:

media-libs/gst-plugins-bad (0.10.23-r4(0.10)@17/09/17 1.12.3(1.0)@24/10/17)
media-libs/gst-plugins-base (0.10.36-r2(0.10)@05/09/15 1.12.3(1.0)@20/09/17)
media-libs/gst-plugins-good (0.10.31-r2(0.10)@14/06/16 1.12.3(1.0)@20/09/17)
media-libs/gst-plugins-ugly (0.10.19-r1(0.10)@05/09/15 1.12.3(1.0)@20/09/17)
media-plugins/gst-plugins-a52dec (0.10.19-r1(0.10)@05/09/15 1.12.3(1.0)@20/09/17)
media-plugins/gst-plugins-alsa (0.10.36-r1(0.10)@02/09/15)
media-plugins/gst-plugins-assrender (0.10.23-r1(0.10)@03/02/17 1.12.3(1.0)@20/09/17)
media-plugins/gst-plugins-cdparanoia (0.10.36-r1(0.10)@02/09/15 1.12.3(1.0)@20/09/17)
media-plugins/gst-plugins-dts (0.10.23-r1(0.10)@05/09/15 1.12.3(1.0)@20/09/17)
media-plugins/gst-plugins-dv (0.10.31-r1(0.10)@02/09/15 1.12.3(1.0)@20/09/17)
media-plugins/gst-plugins-dvdread (0.10.19-r1(0.10)@02/09/15 1.12.3(1.0)@20/09/17)
media-plugins/gst-plugins-faad (0.10.23-r2(0.10)@02/09/15 1.12.3(1.0)@20/09/17)
media-plugins/gst-plugins-flac (0.10.31-r1(0.10)@02/09/15 1.12.3(1.0)@20/09/17)
media-plugins/gst-plugins-ladspa (0.10.23-r1(0.10)@16/06/17)
media-plugins/gst-plugins-lame (0.10.19-r1(0.10)@02/09/15 1.12.3(1.0)@20/09/17)
media-plugins/gst-plugins-libav (1.12.3(1.0)@20/09/17)
media-plugins/gst-plugins-mad (0.10.19-r1(0.10)@02/09/15 -> 0.10.19-r1(0.10)^t 1.10.5(1.0)^t)
media-plugins/gst-plugins-meta (0.10-r11(0.10)@02/02/17 1.12.3(1.0)@26/10/17)
media-plugins/gst-plugins-mpeg2dec (0.10.19-r1(0.10)@02/09/15 1.12.3(1.0)@20/09/17)
media-plugins/gst-plugins-mpg123 (1.12.3(1.0)@26/10/17)
media-plugins/gst-plugins-musepack (0.10.23-r1(0.10)@02/09/15)
media-plugins/gst-plugins-ogg (0.10.36-r1(0.10)@02/09/15)
media-plugins/gst-plugins-opus (0.10.23-r1(0.10)@02/09/15 1.12.3(1.0)@20/09/17)
media-plugins/gst-plugins-resindvd (0.10.23-r1(0.10)@02/09/15 1.12.3(1.0)@20/09/17)
media-plugins/gst-plugins-soup (1.12.3(1.0)@20/09/17)
media-plugins/gst-plugins-taglib (0.10.31-r1(0.10)@08/04/16 1.12.3(1.0)@20/09/17)
media-plugins/gst-plugins-theora (0.10.36-r1(0.10)@02/09/15)
media-plugins/gst-plugins-vorbis (0.10.36-r1(0.10)@02/09/15)
media-plugins/gst-plugins-wavpack (0.10.31-r1(0.10)@02/09/15 1.12.3(1.0)@20/09/17)
media-plugins/gst-plugins-x (0.10.36-r1(0.10)@02/09/15)
media-plugins/gst-plugins-x264 (0.10.19-r1(0.10)@26/07/17 1.12.3(1.0)@20/09/17)
media-plugins/gst-plugins-xvid (0.10.23-r1(0.10)@02/09/15)
media-plugins/gst-plugins-xvideo (0.10.36-r1(0.10)@02/09/15)

**Comment by otsaloma** [comment]
As far as I can tell you have the relevant stuff: base, good, bad, ugly and libav, version 1.12.3.

Two things you can try.

1. Start Gaupol from a terminal and see if you get any error output there.

2. Try playing the same video in another GStreamer-based video player, e.g. Totem and see if that works. If you need to install another video player, also try Gaupol again after that in case it installed some missing dependencies.

**Comment by luisjure** [comment]
thanks for answer!

1. that's the first thing i tried, but i couldn't find anything terribly useful or relevant to this problem.

when i open a subtitle file, i see a bunch of:
(python3.5:5100): Gtk-WARNING **: Allocating size to GtkApplicationWindow 0x1d0e2b0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

when i open the window to open a video i get one lonely:
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

when closing the application after failing to load a video, this message appeared once:
(python3.5:5100): Gtk-CRITICAL **: gtk_range_set_value: assertion 'GTK_IS_RANGE (range)' failed

2. i don't know, gaupol always worked for me, so it can't be a missing dependency. i assume that something broke after updating a plugin or something, but i have no idea what it could be.

**Comment by luisjure** [comment]
thanks for answer!

1. that's the first thing i tried, but i couldn't find anything terribly useful or relevant to this problem.

when i open a subtitle file, i see a bunch of:
(python3.5:5100): Gtk-WARNING **: Allocating size to GtkApplicationWindow 0x1d0e2b0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

when i open the window to open a video i get one lonely:
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

when closing the application after failing to load a video, this message appeared once:
(python3.5:5100): Gtk-CRITICAL **: gtk_range_set_value: assertion 'GTK_IS_RANGE (range)' failed

2. i don't know, gaupol always worked for me, so it can't be a missing dependency. i assume that something broke after updating a plugin or something, but i have no idea what it could be.

**Comment by otsaloma** [comment]
Those first two warnings are harmless and the third one probably relates to the position slider and it's a symptom of the same problem.

I don't really have any other ideas. The relevant part of the code that fails (as far as I can tell) is rather simple and likely some kind of codec trouble. That is assuming this happens for multiple files, for a single file, it could be a broken file as well.

https://github.com/otsaloma/gaupol/blob/c97e63b44324d183e28631ceb8935304318b6a3e/gaupol/player.py#L143

I recommend you ask Gentoo's forums or file a bug against the Gentoo package. Considering that some update outside Gaupol apparently brought this on, maybe they can help better.

**Comment by luisjure** [comment]
thanks, i'll see if i can gather more definite information for a bug report at gentoo bugzilla.

great software, by the way, thanks.

**Comment by Pemicope** [comment]
Hello.

I'm having the same problem with Ubuntu Budgie 17.10.

**Traceback:**

File: /usr/local/lib/python3.6/dist-packages/gaupol/agents/video.py
Line: 198
In: _on_load_video_activate

    self.load_video(path)

File: /usr/local/lib/python3.6/dist-packages/gaupol/agents/video.py
Line: 161
In: load_video

    self._init_player_widgets()

File: /usr/local/lib/python3.6/dist-packages/gaupol/agents/video.py
Line: 129
In: _init_player_widgets

    self.player = gaupol.VideoPlayer()

File: /usr/local/lib/python3.6/dist-packages/gaupol/player.py
Line: 74
In: __init__

    self._init_pipeline()

File: /usr/local/lib/python3.6/dist-packages/gaupol/player.py
Line: 162
In: _init_pipeline

    self.widget.pack_start(sink.props.widget, True, True, 0)

AttributeError: 'NoneType' object has no attribute 'props'

Environment

Platform: Linux-4.13.0-16-generic-x86_64-with-Ubuntu-17.10-artful
Locale: pt_PT.utf_8

Versions

aeidon: 1.3.1
chardet: 3.0.4
enchant: 1.6.7
gaupol: 1.3.1
gstreamer: 1.12.3.0
gtk+: 3.22.25
pygobject: 3.24.1
python: 3.6.3

I hope you find a solution, thanks!

**Comment by otsaloma** [comment]
@Pemicope Please open a new issue, that's not the same problem.

**Comment by luisjure** [comment]
just for the record, the problem disappeared some time ago, and gaupol 1.3.1 works perfectly all right now.

**Comment by otsaloma** [comment]
Thanks for the update, I'll close this issue as no one else has reported on being affected.
