### ISSUE TITLE
pango warning entity escape ampersand

### ISSUE THREAD

**Issue by goatscrub** [otsaloma/gaupol#74]
Hi,

First of all, thank for your great work, I use gaupol frequently.

I discover an issue with pango markup when a subtitle contain a specific entity like the ampersand in it.
If a subtitle contains a non-escaped ampersand ("Youth & Government" for example), the gaupol video player drops subtitle content and display previous subtitle content in place.
The written file is not affected by this issue, as well as the external video player, this only occurs with the "internal" video player.

I test it with github version 1.3.1, console message is:

`(gaupol:6698): Pango-WARNING **: pango_layout_set_markup_with_accel: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity - escape ampersand as &amp;
`

Similar case also exist with "<" char when it is alone, video player drops subtitle content and display previous subtitle, console message is different:

`(gaupol:7930): Pango-WARNING **: pango_layout_set_markup_with_accel: Error on line 1 char 12: '<' is not a valid name
`

Sorry for my approximative english, I hope you understand the main idea, thanks.

**Comment by otsaloma** [comment]
Thanks, I understand. The subtitle text just likely needs a  `GLib.markup_escape_text` call, I'll fix it.
