### ISSUE TITLE
--video-file=FILE flag does not work (opens with only subtitles)

### ISSUE THREAD

**Issue by listedegarde** [otsaloma/gaupol#75]
The -v, --video-file flag does not seem to work.  The srt file opens all by itself, and no video file is opened.  No errors occur in the terminal (other than a GTK-warning: "Gtk-WARNING **: Allocating size to GtkApplicationWindow 0x2f4a2a0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?").  Various methods I have tried:

- gaupol -v file.mp4 file.srt
- gaupol -v=file.mp4 file.srt
- gaupol --video-file file.mp4 file.srt
- gaupol --video-file=file.mp4 file.srt

And I have tried inverting the "srt" and -v file.mp4 as well for all 4 commands.

The real reason I wanted this is because when I open a SRT file, I want it to open the MP4 file at the same time.  I thought that I could simply create a bash script, but since the flag is not working, I cannot.

So as a suggestion, I would say see if you can add an option to automatically open the video file in the same folder with the same name when opening the SRT file.

**Edit**: I forgot to mention that I am using Ubuntu 18.04 with Gaupol 1.3.1

**Comment by otsaloma** [comment]
The `--video-file` argument predates the internal video player and what it does is the same as "Select Video" from the "Tools" menu. It basically selects the video used by the _external_ video player. If your filenames differ only in the extension, e.g. `file.mp4` and `file.srt`, then the selection is automatic and no need to specify it.

But yes, by now, I guess it should load the video in the internal player. I'll fix it.
