### ISSUE TITLE
seek selection start on subtitle begining before 1 second

### ISSUE THREAD

**Issue by goatscrub** [otsaloma/gaupol#76]
Hi,

I don't know if it a feature, but I noticed that it's not possible to seek on a subtitle if its start time is less than one second (00:00:00.000 to 00:00:00.999), console message is:

`(gaupol:8152): GStreamer-CRITICAL **: gst_element_seek_simple: assertion 'seek_pos >= 0' failed`

I tried to find origin and I found that pos in seek() (gaupol/player.py) value is always one second less than subtitle start time regardless of offset in preferences. I don't understand why after a deep search into time calculation, so I temporary fixed that with an uggly:

`if pos < 0: pos = 0`

Thanks again for your work.

**Comment by otsaloma** [comment]
I can't reproduce this. Are you using the latest version? By seek, do you mean "Seek Backwards" (Shift+Ctrl+Left) or "Seek Previous" (Ctrl+Left)?

**Comment by goatscrub** [comment]
Apparently I posted my last two issues too fast, one already exists and other is incomplete, sorry about that.
So, by seek I mean "CTRL+UP" or "seek selection start" in subtitle's contextual menu, I am using hotkey often, it is really amazing.
My srt file look likes this:
`
1
00:00:00,555 --> 00:00:03,000
first

2
00:00:03,000 --> 00:00:06,000
second

3
00:00:06,000 --> 00:00:09,000
third
`
In this example, if you try to "seek selection start" on "first" subtitle, it doesn't work as expected, because pos variable is negative and you get message in my previous post.
To be sure, I update my local repository and it remains the same.

**Comment by otsaloma** [comment]
Ah, yes, now I found the problem. I'll fix it.
