### ISSUE TITLE
Feature-request: 3D subtitles

### ISSUE THREAD

**Issue by jolpe** [otsaloma/gaupol#81]
I'm using gaupol 1.3.1 and I'd like to be able to convert normal subtitles into 3D and save those. I've tried to explore all the options and tools gaupol offers but I've failed to find one that would allow on create/convert/save pre-existing subtitles into 3D as in either Side-by-Side or Over-Under. Therefore this request.

So far my only option has been website http://subtitle3d.com/ which provides rather nice interface and options to do the task required. Something that gaupol could and even should mimic to certain extent. I find the social media buttons bit too much.

![subtitle3d com](https://user-images.githubusercontent.com/22399699/37768876-cc08085c-2dd7-11e8-9c34-68b0f1112ea2.png)

**Comment by otsaloma** [comment]
Maybe a cool thing, but a very niche feature. I don't really expect to do this, nor does it really need to be a part of Gaupol as opposed to a stand-alone app.
