### ISSUE TITLE
Error retrieving accessibility bus address (Gaupol 1.3.1)

### ISSUE THREAD

**Issue by WPFilmmaker** [otsaloma/gaupol#82]
While I was runnng the latest version of Gaupol I noticed that in the terminal a warning appear. I don't know whether it can be ignored or not, I felt to report it. It seems not affecting the usage of the software (so far).

`** (gaupol:3777): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files`

I am on Lubuntu 16.04.3 Gaupol 1.3.1

**Comment by otsaloma** [comment]
Gaupol doesn't directly use any accessibility stuff, so this is likely something misconfigured in the GTK accessibility stack. It if doesn's affect your use, then no need to look into it.
