### ISSUE TITLE
gtksink not found anymore with GStreamer 1.14

### ISSUE THREAD

**Issue by Raghnarok** [otsaloma/gaupol#83]
I can't open video anymore. I got this traceback :

> Traceback
>
>File: /usr/share/gaupol/gaupol/agents/video.py
>Line: 198
>In: _on_load_video_activate
>
>    self.load_video(path)
>
>File: /usr/share/gaupol/gaupol/agents/video.py
>Line: 161
>In: load_video
>
>    self._init_player_widgets()
>
>File: /usr/share/gaupol/gaupol/agents/video.py
>Line: 129
>In: _init_player_widgets
>
>    self.player = gaupol.VideoPlayer()
>
>File: /usr/share/gaupol/gaupol/player.py
>Line: 74
>In: __init__
>
>    self._init_pipeline()
>
>File: /usr/share/gaupol/gaupol/player.py
>Line: 162
>In: _init_pipeline
>
>    self.widget.pack_start(sink.props.widget, True, True, 0)
>
>AttributeError: 'NoneType' object has no attribute 'props'
>
>Environment
>
>Platform: Linux-4.15.0-2-amd64-x86_64-with-debian-buster-sid
>Locale: fr_CH.utf_8
>
>Versions
>
>aeidon: 1.3.1
>chardet: 3.0.4
>enchant: 2.0.0
>gaupol: 1.3.1
>gstreamer: 1.14.0.0
>gtk+: 3.22.29
>pygobject: 3.26.1
>python: 3.6.5

Dunno what changed, but all was working fine the last time I used Gaupol, like 2-3 days ago...

**Comment by edoput** [comment]
I got the very same bug report, I'll add my environment details as the traceback is the same

```
Environment

Platform: Linux-4.15.0-2-amd64-x86_64-with-debian-buster-sid
Locale: en_US.utf_8

Versions

aeidon: 1.3.1
chardet: 3.0.4
enchant: 2.0.0
gaupol: 1.3.1
gstreamer: 1.14.0.0
gtk+: 3.22.29
pygobject: 3.26.1
python: 3.6.5
```

The problem is located [here](https://github.com/otsaloma/gaupol/blob/master/gaupol/player.py#L162) as I don't have a gtksink element available on my machine.

I searched for `gtkstink` using `gst-inspect-1.0 gtksink` but got nothing

**Comment by otsaloma** [comment]
This seems to be related to the recent GStreamer 1.14. The release note state that "The GTK+ plugin has also moved from -bad to -good. It includes gtksink and gtkglsink which both render video into a GtkWidget." But, I can't seem to find gtksink in good either. I'll look into it.

**Comment by otsaloma** [comment]
It seems Debian just builds a separate package for gtk-sink now, you need to install "gstreamer1.0-gtk3". I just filed a bug report on the Gaupol Debian package to get the dependencies updated.

**Comment by otsaloma** [comment]
Also, for the record, GStreamer dependency checks were updated already [earlier](https://github.com/otsaloma/gaupol/commit/daefc057700ae610f2fbafb01048c3a2ed51e528), so that traceback shouldn't happen anymore if gtksink is missing, there should be a helpful console message instead.
