### ISSUE TITLE
Support for text formatting

### ISSUE THREAD

**Issue by WPFilmmaker** [otsaloma/gaupol#84]
Hi, at the moment it is not possible changing specs of the character like font,color,size (at the least I couldn't find it, if it is possible let me know please). It would be nice to have such options either via a right click menu on the text "line" or on the top bar (perhaps under "text"). It would be useful for when more than one person is talking or for annotation.

Some fonts are free to use like:
https://www.gnu.org/software/freefont/
http://overpassfont.org/
https://en.wikipedia.org/wiki/Liberation_fonts

**Comment by otsaloma** [comment]
It's already possible to do formatting, but of course very inconvenient as you need to know the format-specific markup tags and type them manually. The only common form of formatting, italics, is available in the text menu, affecting an entire subtitle.

There's different schools of thought on the matter, and Gaupol is, mostly intentionally, aligned with those who find various formatting more of a distraction than helpful. I understand some use cases are legitimate, but it's a difficult UI issue, both in terms of controls and display, difficult in terms of file format and video player support, and a slippery slope in general. So, a lot of work for little gain. It's unlikely that we'll go in that direction. There's at least [Aegisub](http://www.aegisub.org/) and Kitone's [Subtitle Editor](http://kitone.github.io/subtitleeditor/) who have already taken this very far.

**Comment by otsaloma** [comment]
I'll close this as it's really unlikely that we'll go in this direction.

**Comment by IoIxD** [comment]
can you give me an editor that does support this please?
