### ISSUE TITLE
Can't load video

### ISSUE THREAD

**Issue by volkerbradley** [otsaloma/gaupol#86]
Traceback

File: /home/volker/Downloads/gaupol-1.3.1/gaupol/agents/video.py
Line: 198
In: _on_load_video_activate

    self.load_video(path)

File: /home/volker/Downloads/gaupol-1.3.1/gaupol/agents/video.py
Line: 161
In: load_video

    self._init_player_widgets()

File: /home/volker/Downloads/gaupol-1.3.1/gaupol/agents/video.py
Line: 129
In: _init_player_widgets

    self.player = gaupol.VideoPlayer()

File: /home/volker/Downloads/gaupol-1.3.1/gaupol/player.py
Line: 74
In: __init__

    self._init_pipeline()

File: /home/volker/Downloads/gaupol-1.3.1/gaupol/player.py
Line: 162
In: _init_pipeline

    self.widget.pack_start(sink.props.widget, True, True, 0)

AttributeError: 'NoneType' object has no attribute 'props'

Environment

Platform: Linux-4.15.0-18-generic-x86_64-with-Ubuntu-18.04-bionic
Locale: en_US.utf_8

Versions

aeidon: 1.3.1
chardet: 3.0.4
enchant: None
gaupol: 1.3.1
gstreamer: 1.14.0.0
gtk+: 3.22.30
pygobject: 3.26.1
python: 3.6.5

**Comment by otsaloma** [comment]
This is likely the same as #83, see the second last comment for the solution.
