### ISSUE TITLE
Installs the file custom-framerates.cpython-36.pyo that is't in plist

### ISSUE THREAD

**Issue by yurivict** [otsaloma/gaupol#91]
When the ```plist.txt``` is built with this command ```python setup.py install --record plist.txt```, this file doesn't appear in the ```plist.txt```:
```share/gaupol/extensions/custom-framerates/__pycache__/custom-framerates.cpython-36.pyo```

Please either make it appear there, or don't install it.

**Comment by otsaloma** [comment]
Maybe the extensions wouldn't need to be compiled, but I added them, so they should now be included in the list. A bit hacky as `byte_compile` doesn't return the filenames, but should work.
